#!/usr/bin/env python3
"""
make_diagrams.py

Three plates that carry numbers rather than geometry, drawn in three
dimensions so that the numbers can be read against one another.

  fig_ladder     the Betti numbers binom(8,k) of an abelian fourfold as
                 prisms, each split into the image of the Lefschetz operator
                 and the primitive part, with the hard Lefschetz
                 isomorphisms L^{4-k} : H^k -> H^{8-k} drawn as arcs at
                 different depths; the primitive middle part, of dimension
                 70 - 28 = 42, is the clay block.

  fig_moduli     for n = 1..6, a stacked prism of height n(2n+1), the
                 dimension of the moduli of principally polarised abelian
                 2n-folds, split into the Weil family of dimension n^2 and
                 its codimension n(n+1).

  fig_signature  the signatures (p,q) of an imaginary quadratic action, with
                 p + q = dim A, on the surface of height pq, which is the
                 dimension of the family of abelian varieties with that
                 action.  The antidiagonals collect the signatures available
                 in one dimension; the ridge p = q is where the Weil line
                 consists of Hodge classes, and on each antidiagonal it is
                 the highest point.

All heights are the actual numbers, times one scale per figure.
"""
import math
import os
import sys
from math import comb

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from render3d import Camera, Scene
from place import Placer

HEAD = r"""%% {name}.tex   (generated by make_diagrams.py; do not edit by hand)
%% {blurb}
\documentclass[tikz,border=8pt]{{standalone}}
\usepackage{{amsmath,amssymb}}
\usetikzlibrary{{arrows.meta,calc}}
\input{{palette}}
\begin{{document}}
\begin{{tikzpicture}}[x=1cm,y=1cm,line join=round,line cap=round,
  font=\small,text=PInk]
"""
TAIL = "\\end{tikzpicture}\n\\end{document}\n"


def write(name, blurb, sc, P):
    body = sc.emit()
    bad = P.check(body, sc.cam)
    if bad:
        raise SystemExit("placement failure in %s: %s" % (name, bad))
    labels = P.emit(body, sc.cam)
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, name + ".tex"), "w") as f:
        f.write(HEAD.format(name=name, blurb=blurb))
        f.write(body)
        f.write(labels)
        f.write(TAIL)
    print("%-18s %2d labels, clear of the ink and of each other"
          % (name, len(P.items)))


def ground(sc, x0, x1, y0, y1, nx, ny, z=0.0):
    sc.surface(lambda u, v: (u, v, z), (x0, x1), (y0, y1), nx, ny,
               base="PSlate", opacity=0.10, ambient=0.74, diffuse=0.16)
    for k in range(nx + 1):
        x = x0 + (x1 - x0) * k / nx
        sc.polyline([(x, y0, z), (x, y1, z)], "PRule!50,line width=0.15pt",
                    priority=1)
    for k in range(ny + 1):
        y = y0 + (y1 - y0) * k / ny
        sc.polyline([(x0, y, z), (x1, y, z)], "PRule!50,line width=0.15pt",
                    priority=1)


# ------------------------------------------------------------------ ladder
def fig_ladder():
    cam = Camera(eye=(3.2, -11.5, 6.2), target=(0.0, 0.0, 1.35), focal=10.5,
                 scale=2.35)
    sc, P = Scene(cam), Placer()
    H = 0.045
    W = 0.58
    X = [-3.6 + 0.9 * k for k in range(9)]
    b = [comb(8, k) for k in range(9)]
    prim = [b[k] - (b[k - 2] if k >= 2 else 0) for k in range(5)]
    ground(sc, -4.2, 4.2, -1.7, 0.7, 14, 4)
    tops = []
    for k in range(9):
        x = X[k]
        if k <= 4:
            low = b[k] - prim[k]
            if low:
                sc.box((x, 0, low * H / 2), (W, W, low * H), base="PSlate",
                       opacity=0.72, edge_style="PSlate!70!black,line width=0.3pt")
            colr = "PClay" if k == 4 else "PIndigo"
            sc.box((x, 0, low * H + prim[k] * H / 2), (W, W, prim[k] * H),
                   base=colr, opacity=0.78 if k == 4 else 0.55,
                   edge_style="%s!75!black,line width=0.35pt" % colr)
        else:
            sc.box((x, 0, b[k] * H / 2), (W, W, b[k] * H), base="PSlate",
                   opacity=0.60, edge_style="PSlate!70!black,line width=0.3pt")
        tops.append((x, 0, b[k] * H))
    # the arcs L^{4-k}: H^k -> H^{8-k}, at increasing depth behind the bars
    arc_mid = []
    for k in range(4):
        xa, xb = X[k], X[8 - k]
        ya = 0.55 + 0.32 * (3 - k)
        za = b[k] * H
        zb = b[8 - k] * H
        top = 3.35 + 0.30 * (3 - k)

        def arc(t, xa=xa, xb=xb, ya=ya, za=za, zb=zb, top=top):
            x = xa + (xb - xa) * t
            z = (1 - t) * za + t * zb + (top - max(za, zb)) * math.sin(math.pi * t)
            return (x, ya * math.sin(math.pi * t), z)
        pts = [arc(i / 60.0) for i in range(61)]
        sc.arrow(pts, "PBlue,line width=%.2fpt" % (0.9 + 0.15 * k), priority=4)
        arc_mid.append(arc(0.5))
    for k in range(9):
        P.add(tops[k], r"$H^{%d}$, %d" % (k, b[k]),
              "text=PClay" if k == 4 else "text=PInk",
              side="L" if k < 4 else "R")
    for k in range(4):
        P.add(arc_mid[k], r"$L^{%d}$" % (4 - k), "text=PBlue",
              side="L" if k % 2 == 0 else "R")
    P.add((X[4], 0, (b[4] - prim[4] / 2.0) * H),
          r"primitive part of $H^{4}$, $70-28=42$", "text=PClay", side="R")
    write("fig_ladder",
          "Betti numbers of an abelian fourfold as prisms, split into the "
          "Lefschetz image and the primitive part, with the hard Lefschetz "
          "arcs.", sc, P)


# ------------------------------------------------------------------ moduli
def fig_moduli():
    cam = Camera(eye=(7.5, -10.0, 6.0), target=(0.0, 0.0, 1.45), focal=10.5,
                 scale=2.45)
    sc, P = Scene(cam), Placer()
    H = 0.042
    W = 0.52
    ground(sc, -3.4, 3.4, -1.0, 1.0, 12, 4)
    xs = [-2.75 + 1.1 * (n - 1) for n in range(1, 7)]
    topA, topD, midG = [], [], []
    for n, x in zip(range(1, 7), xs):
        d = n * n
        g = n * (n + 1)
        sc.box((x, 0, d * H / 2), (W, W, d * H), base="PBlue", opacity=0.78,
               edge_style="PBlue!75!black,line width=0.35pt")
        sc.box((x, 0, d * H + g * H / 2), (W, W, g * H), base="PClay",
               opacity=0.55, edge_style="PClay!75!black,line width=0.35pt")
        topA.append((x, 0, (d + g) * H))
        topD.append((x, 0, d * H))
        midG.append((x, 0, (d + g / 2.0) * H))
    for n in range(6):
        P.add((xs[n], 0, 0), r"$n=%d$" % (n + 1), "text=PSlate",
              side="L" if n < 3 else "R")
    P.add(topA[5], r"$\dim\mathcal{A}_{2n}=n(2n+1)$, here $78$", "text=PClay",
          side="R")
    P.add(midG[5], r"codimension $n(n+1)$, here $42$", "text=PClay",
          side="R")
    P.add(topD[5], r"$\dim\mathcal{D}_{n,n}=n^{2}$, here $36$", "text=PBlue",
          side="R")
    P.add(topA[1], r"$n=2$: $10=4+6$", "text=PInk", side="L")
    P.add(topA[2], r"$n=3$: $21=9+12$", "text=PInk", side="L")
    write("fig_moduli",
          "The Weil family inside the moduli of principally polarised abelian "
          "2n-folds: n^2 against n(2n+1), for n up to six.", sc, P)


# --------------------------------------------------------------- signature
def fig_signature():
    cam = Camera(eye=(-7.0, -10.5, 8.2), target=(0.3, 0.3, 0.9), focal=10.8,
                 scale=2.30)
    sc, P = Scene(cam), Placer()
    S = 0.36          # lattice spacing
    Hs = 0.050        # height per unit of pq
    N = 12

    def pt(p, q):
        return ((p - N / 4.0) * S, (q - N / 4.0) * S, p * q * Hs)

    # the surface z = pq over the triangle p + q <= 12, as a fine mesh
    sc.surface(lambda u, v: ((u - N / 4.0) * S, (v - N / 4.0) * S, u * v * Hs),
               (0.0, float(N)), (0.0, float(N)), 24, 24, base="PSlate",
               opacity=0.26, ambient=0.60, diffuse=0.34,
               cull=lambda Q: all((q[0] / S + N / 4.0) + (q[1] / S + N / 4.0)
                                  <= N + 1e-9 for q in Q))
    ground(sc, -N / 4.0 * S, 3 * N / 4.0 * S, -N / 4.0 * S, 3 * N / 4.0 * S,
           12, 12)
    # antidiagonals p + q = 2m on the surface, one per even dimension
    ends = []
    for m in range(1, 7):
        s = 2 * m
        sc.curve(lambda t, s=s: (((t) - N / 4.0) * S, ((s - t) - N / 4.0) * S,
                                 t * (s - t) * Hs),
                 (0.0, float(s)), 12 * m, "PSlate!80,line width=0.55pt",
                 priority=2, chunk=2)
        for p in range(0, s + 1):
            q = s - p
            if p == q:
                continue
            sc.dot3(pt(p, q), "circle,draw=PSlate,fill=white,line width=0.4pt,"
                    "inner sep=1.0pt", priority=5)
        ends.append(pt(s, 0))
    # the ridge p = q, where the Weil line consists of Hodge classes
    sc.curve(lambda t: pt(t, t), (0.0, 6.0), 60, "PClay,line width=1.5pt",
             priority=4, chunk=2)
    for n in range(1, 7):
        sc.dot3(pt(n, n), "circle,fill=PClay,draw=white,line width=0.6pt,"
                "inner sep=1.9pt", priority=6)
        sc.polyline([(pt(n, n)[0], pt(n, n)[1], 0.0), pt(n, n)],
                    "PClay!60,line width=0.35pt,dash pattern=on 1pt off 1.2pt",
                    priority=3)
    for m in range(6):
        P.add(ends[m], r"$\dim A=%d$" % (2 * (m + 1)), "text=PSlate",
              side="R")
    P.add(pt(6, 6), r"$p=q$: Weil type, $\dim\mathcal{D}_{n,n}=n^{2}$",
          "text=PClay", side="L")
    P.add(pt(3, 3), r"$(3,3)$, height $9$", "text=PClay", side="L")
    P.add(pt(0, 12), r"$q$", "text=PSlate", side="L")
    P.add(pt(12, 0), r"$p$", "text=PSlate", side="R")
    P.add(pt(1, 1), r"height $pq$, the dimension of the family",
          "text=PSlate", side="L")
    write("fig_signature",
          "The signatures (p,q) of an imaginary quadratic action on the "
          "surface of height pq, with the Weil ridge p = q.", sc, P)


if __name__ == "__main__":
    fig_ladder()
    fig_moduli()
    fig_signature()
