#!/usr/bin/env python3
"""
make_secant.py

One plate for the existence theorem of the third ingredient.

  fig_moment   the secant plane P_t, the moment curve carrying the Chern
               characters of the powers of one line bundle, the integral
               points of the plane sorted into those the line bundles reach
               and those they do not, and the doubling that repairs the gap

Nothing is drawn by eye.  The coordinates are the real ones: a class in
Q[t]/(t^3) is written in the basis 1, t, t^2/2 as a triple (c_0,c_1,c_2), the
line bundle O(j t) sits at (1,j,j^2) on the moment curve, the plane P_t at
d = 2 is the span of u = (1,0,-2) and v = (0,1,0), and the lattice spanned by
the moment points is exactly {(x,y,z) : z = y mod 2}.  The third coordinate is
drawn at two fifths scale so that the parabola and the plane share a frame.
"""
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from render3d import Camera, Scene
from place import Placer

HEAD = r"""%% {name}.tex   (generated by make_secant.py; do not edit by hand)
%% {blurb}
\documentclass[tikz,border=8pt]{{standalone}}
\usepackage{{amsmath,amssymb}}
\usetikzlibrary{{arrows.meta,calc}}
\input{{palette}}
\begin{{document}}
\begin{{tikzpicture}}[x=1cm,y=1cm,line join=round,line cap=round,
  font=\small,text=PInk]
"""
TAIL = "\\end{tikzpicture}\n\\end{document}\n"

ZS = 0.40                      # drawing scale on the third coordinate


def write(name, blurb, sc, P):
    body = sc.emit()
    bad = P.check(body, sc.cam)
    if bad:
        raise SystemExit("placement failure in %s: %s" % (name, bad))
    labels = P.emit(body, sc.cam)
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, name + ".tex"), "w") as f:
        f.write(HEAD.format(name=name, blurb=blurb))
        f.write(body)
        f.write(labels)
        f.write(TAIL)
    print("%-18s %2d labels, clear of the ink and of each other"
          % (name, len(P.items)))


def pt(c0, c1, c2):
    """A class (c_0,c_1,c_2) placed in the drawing frame."""
    return (c0, c1, ZS * c2)


def fig_moment():
    d, a, b = 2, 1, 1
    cam = Camera(eye=(8.6, -9.4, 5.6), target=(0.45, 0.10, 0.10), focal=9.0,
                 scale=3.50)
    sc, P = Scene(cam), Placer()

    # ---- the secant plane P_t = span( u = (1,0,-d), v = (0,1,0) )
    sc.surface(lambda s, r: pt(s, r, -d * s), (-1.15, 2.35), (-2.35, 2.35),
               26, 30, base="PIndigo", opacity=0.62, ambient=0.32,
               diffuse=0.34)

    # ---- the three coordinate axes, drawn short and unobtrusive
    for e, lab in (((1, 0, 0), None), ((0, 1, 0), None), ((0, 0, 1), None)):
        sc.polyline([pt(-0.9 * e[0], -1.9 * e[1], -3.3 * e[2]),
                     pt(2.5 * e[0], 2.6 * e[1], 4.6 * e[2])],
                    "PSlate!70,line width=0.55pt,dash pattern=on 2pt off 2pt",
                    priority=0)

    # ---- the moment curve j -> ch O(j t) = (1, j, j^2)
    sc.curve(lambda j: pt(1.0, j, j * j), (-1.35, 2.45), 180,
             "PTeal,line width=1.25pt", chunk=2)
    for j in (-1, 0, 1, 2):
        sc.dot3(pt(1.0, j, j * j),
                "circle,fill=PTeal,draw=white,line width=0.55pt,inner sep=2.0pt",
                priority=5)

    # ---- the witness: -3 [O] + 8 [O(t)] - 3 [O(2t)] = 2 p
    for j, w in ((0, -3), (1, 8), (2, -3)):
        sc.polyline([pt(1.0, j, j * j), pt(2 * a, 2 * b, -2 * d * a)],
                    "PAmber!80,line width=0.6pt,dash pattern=on 1.4pt off 1.6pt",
                    priority=1)
        del w

    # ---- the integral points of the plane, sorted by reachability
    #      (x,y,-d x) lies in the line bundle lattice iff -d x = y mod 2
    for x in (-1, 0, 1, 2):
        for y in (-2, -1, 0, 1, 2):
            reach = ((-d * x - y) % 2 == 0)
            style = ("circle,fill=PGrass,draw=white,line width=0.5pt,"
                     "inner sep=1.7pt") if reach else \
                    ("circle,draw=PMag,line width=0.8pt,fill=white,"
                     "inner sep=1.5pt")
            sc.dot3(pt(x, y, -d * x), style, priority=4)

    # ---- the rational point p and its double
    sc.polyline([pt(0, 0, 0), pt(2 * a, 2 * b, -2 * d * a)],
                "PMag,line width=1.05pt,-{Stealth[length=4.2pt]}", priority=3)
    sc.dot3(pt(a, b, -d * a),
            "circle,draw=PMag,line width=1.1pt,fill=white,inner sep=2.2pt",
            priority=6)
    sc.dot3(pt(2 * a, 2 * b, -2 * d * a),
            "circle,fill=PMag,draw=white,line width=0.6pt,inner sep=2.4pt",
            priority=6)
    sc.dot3(pt(0, 0, 0), "circle,fill=PInk,inner sep=1.5pt,draw=none",
            priority=6)

    P.add(pt(2.5, 0.0, 0.0), r"$\ch_{0}$", "text=PSlate", side="R")
    P.add(pt(0.0, 2.6, 0.0), r"$\ch_{1}$", "text=PSlate", side="R")
    P.add(pt(0.0, 0.0, 4.6), r"$\ch_{2}$", "text=PSlate", side="L")
    P.add(pt(1.0, 2.45, 6.0), r"$\ch\,\cO(jt)=(1,j,j^{2})$",
          "text=PTeal", side="R")
    P.add(pt(-1.15, -2.35, 2.3), r"$P_{t}$, at $d=2$",
          "text=PIndigo", side="L")
    P.add(pt(a, b, -d * a), r"$p=u_{t}+v_{t}$",
          "text=PMag", side="L")
    P.add(pt(2 * a, 2 * b, -2 * d * a),
          r"$2p$, reached", "text=PMag", side="R")
    P.add(pt(-1, 2, 2), r"reached",
          "text=PGrass", side="L")
    P.add(pt(1, -1, -2), r"missed",
          "text=PMag", side="L")
    write("fig_moment",
          "The secant plane, the moment curve of line bundle Chern "
          "characters, and the multiple that lands a rational point of the "
          "plane on the lattice they span.",
          sc, P)


if __name__ == "__main__":
    fig_moment()
