#!/usr/bin/env python3
"""
make_round12.py

Two plates for the results of round twelve.

  fig_minimalsupport  the minimal support theorem at n = 4, for X very
                      general: the Chern characters of the natural objects on
                      the split member X x Xhat (line bundles, subtori, points
                      and their Fourier-Mukai images) are the Veronese images
                      of the rational points of a quadric threefold Q, those
                      of the powers of the polarisation are the points of one
                      conic C_theta, and the Weil line is spanned by the two
                      conjugate points L_+ and L_- in which the line l_W meets
                      Q.  A combination of natural characters with a nonzero
                      Weil part needs at least eight rational points off
                      C_theta, and eight suffice only on a smooth conic cut
                      out by a plane through l_W; the eight graph subtori of
                      the explicit relation are drawn on it.

  fig_quarticloci     where the Weil classes of an abelian eightfold of
                      (F,2,delta)-Weil type, F a quartic CM field, are known to
                      be algebraic: the whole family has dimension 8; the
                      Noether-Lefschetz locus of T = wedge^2_F H^1 has
                      components of dimension exactly 6 when delta is trivial
                      and at most 4 otherwise, and the Weil classes are
                      products of divisor classes on it; for F biquadratic the
                      scalar extensions of Weil fourfolds form a locus of
                      dimension 4 on which Markman's theorem applies; the CM
                      points carry the base points of thm:cmbasepoint.  The
                      Hodge-generic member is open.

Every label is written as  \\node[...] at (x,y) {...};  so that checkfigs.py
can read it back and test it for overlaps.
"""
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from make_frontier import box, arrow, line, label, dot  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))

HEAD = r"""%% {name}.tex   (generated by make_round12.py; do not edit by hand)
%% {blurb}
\documentclass[tikz,border=8pt]{{standalone}}
\usepackage{{amsmath,amssymb}}
\usetikzlibrary{{arrows.meta,calc,decorations.pathreplacing}}
\input{{palette}}
\begin{{document}}
\begin{{tikzpicture}}[x=1cm,y=1cm,line join=round,line cap=round,
  font=\small,text=PInk]
"""
TAIL = r"""\end{tikzpicture}
\end{document}
"""


def ellipse_pts(cx, cy, rx, ry, rot=0.0, n=120):
    c, s = math.cos(rot), math.sin(rot)
    pts = []
    for i in range(n + 1):
        t = 2 * math.pi * i / n
        x, y = rx * math.cos(t), ry * math.sin(t)
        pts.append((cx + c * x - s * y, cy + s * x + c * y))
    return pts


def on_ellipse(cx, cy, rx, ry, rot, t):
    c, s = math.cos(rot), math.sin(rot)
    x, y = rx * math.cos(t), ry * math.sin(t)
    return (cx + c * x - s * y, cy + s * x + c * y)


# ----------------------------------------------------------- minimal support
def minimalsupport():
    out = []
    # the quadric threefold, drawn as its outline
    out.append(r"  \fill[WSlate] plot[smooth cycle] coordinates {%s};"
               % " ".join("(%.2f,%.2f)" % p for p in ellipse_pts(0, 0, 4.2, 2.7)[:-1])
               + "\n")
    out.append(line(ellipse_pts(0, 0, 4.2, 2.7), "PSlate", lw=0.8))
    # the conic of the powers of the polarisation
    cth = ellipse_pts(-2.25, 0.95, 1.05, 0.42, rot=0.35)
    out.append(line(cth, "PTeal", lw=1.1))
    # the plane through l_W cuts a smooth conic
    cx, cy, rx, ry, rot = 1.15, -0.55, 2.05, 1.05, -0.18
    out.append(line(ellipse_pts(cx, cy, rx, ry, rot), "PIndigo", lw=1.1))
    # the two conjugate points on it, and the line l_W through them
    tp, tm = 2.55, -0.55
    Lp = on_ellipse(cx, cy, rx, ry, rot, tp)
    Lm = on_ellipse(cx, cy, rx, ry, rot, tm)
    dx, dy = Lm[0] - Lp[0], Lm[1] - Lp[1]
    a = (Lp[0] - 0.16 * dx, Lp[1] - 0.16 * dy)
    b = (Lm[0] + 0.30 * dx, Lm[1] + 0.30 * dy)
    out.append(line([a, b], "PMag", lw=0.9, style=",dash pattern=on 4pt off 2pt"))
    out.append(dot(Lp[0], Lp[1], "PMag", r=2.4, hollow=True))
    out.append(dot(Lm[0], Lm[1], "PMag", r=2.4, hollow=True))
    # eight rational points: the graph subtori of the explicit relation
    ts = [0.35, 0.95, 1.45, 1.95, 3.25, 3.85, 4.45, 5.15]
    for t in ts:
        p = on_ellipse(cx, cy, rx, ry, rot, t)
        out.append(dot(p[0], p[1], "PIndigo", r=2.1))
    # three rational points elsewhere, which cannot reach the Weil line
    for p in ((-1.2, -1.6), (-2.9, -0.75), (0.2, 1.75)):
        out.append(dot(p[0], p[1], "PSlate", r=1.8))
    # labels, outside the ink
    out.append(label(-6.35, 1.55, r"$C_{\theta}$: the powers of $\theta$,"
                     r"\\a conic spanning $\QQ[\theta]$", "PTeal",
                     anchor="west"))
    out.append(label(4.55, 2.35, r"$\ell_{W}$: the Weil line, meeting $Q$ in"
                     r"\\the conjugate points $L_{\pm}$", "PMag",
                     anchor="west"))
    out.append(label(4.55, -1.55, r"a plane through $\ell_{W}$ cuts a smooth"
                     r"\\conic: eight graph subtori $B_{i}$ on it,"
                     r"\\$\sum m_{i}[B_{i}]=14\,W_{2}$ at $d=1$", "PIndigo",
                     anchor="west"))
    out.append(label(-6.35, -1.75, r"$Q$: the quadric of\\Lagrangians;"
                     r" natural\\objects are its\\rational points",
                     "PSlate", anchor="west"))
    out.append(label(0.0, -3.35, r"a nonzero Weil part needs at least eight "
                     r"rational points off $C_{\theta}$, and eight suffice only "
                     r"on such a conic", "PInk"))
    out.append(label(0.0, 3.25, r"minimal support at $n=4$, "
                     r"$X$ very general", "PInk", size=r"\small"))
    return "".join(out)


# ------------------------------------------------------------- quartic loci
def quarticloci():
    out = []

    def panel(x0, title, trivial):
        o = []
        o.append(r"  \fill[WClay,rounded corners=10pt] (%.2f,%.2f) rectangle "
                 r"(%.2f,%.2f);" % (x0, 0.0, x0 + 5.4, 4.2) + "\n")
        o.append(r"  \draw[PClay,line width=0.8pt,rounded corners=10pt] "
                 r"(%.2f,%.2f) rectangle (%.2f,%.2f);"
                 % (x0, 0.0, x0 + 5.4, 4.2) + "\n")
        o.append(label(x0 + 2.7, 4.55, title, "PInk", size=r"\small"))
        # NL(T) components
        if trivial:
            for k, (cx, cy) in enumerate(((x0 + 1.55, 2.75), (x0 + 3.05, 2.35))):
                o.append(r"  \fill[WTeal,opacity=0.9] (%.2f,%.2f) ellipse "
                         r"(%.2f and %.2f);" % (cx, cy, 1.15, 0.62) + "\n")
                o.append(r"  \draw[PGrass,line width=0.8pt] (%.2f,%.2f) "
                         r"ellipse (%.2f and %.2f);" % (cx, cy, 1.15, 0.62)
                         + "\n")
        else:
            for cx, cy in ((x0 + 1.35, 2.85), (x0 + 3.35, 2.65)):
                o.append(r"  \fill[WTeal,opacity=0.9] (%.2f,%.2f) ellipse "
                         r"(%.2f and %.2f);" % (cx, cy, 0.62, 0.30) + "\n")
                o.append(r"  \draw[PGrass,line width=0.8pt] (%.2f,%.2f) "
                         r"ellipse (%.2f and %.2f);" % (cx, cy, 0.62, 0.30)
                         + "\n")
        # scalar-extension locus, dimension 4 (biquadratic F)
        sx0, sy0 = x0 + 0.55, 0.95
        o.append(line([(sx0, sy0), (sx0 + 1.5, sy0 + 0.55), (sx0 + 3.2, sy0 + 0.1),
                       (sx0 + 4.25, sy0 + 0.6)], "POchre", lw=1.3))
        # CM points
        for p in ((x0 + 0.75, 3.55), (x0 + 2.35, 1.95), (x0 + 4.55, 3.4),
                  (x0 + 4.1, 0.45), (x0 + 1.3, 0.45)):
            o.append(dot(p[0], p[1], "PIndigo", r=1.8))
        return o

    out += panel(0.0, r"$\delta$ trivial", True)
    out += panel(7.2, r"$\delta$ nontrivial", False)
    # legend, one statement per line
    rows = [
        (r"clay: the family $\cD_{F}$, of dimension $8$; the Hodge-generic "
         r"member is open", "PClay"),
        (r"grass: the Noether--Lefschetz locus of $T=\bigwedge^{2}_{F}H^{1}$, "
         r"of dimension exactly $6$ ($\delta$ trivial) or at most $4$", "PGrass"),
        (r"\phantom{grass: }on it $W_{F}$ is a sum of products of divisor "
         r"classes", "PGrass"),
        (r"ochre: scalar extensions of Weil fourfolds, dimension $4$ ($F$ "
         r"biquadratic), where Markman's theorem applies", "POchre"),
        (r"indigo: CM points, the base points of the paper", "PIndigo"),
        (r"the quaternion algebra $(F/F_{0},\det H^{-1})$ of $T$ splits "
         r"exactly when $\delta$ is trivial", "PInk"),
    ]
    for k, (txt, col) in enumerate(rows):
        out.append(label(-0.1, -0.75 - 0.5 * k, txt, col, anchor="west"))
    return "".join(out)


def write(name, blurb, body):
    path = os.path.join(HERE, name + ".tex")
    with open(path, "w") as f:
        f.write(HEAD.format(name=name, blurb=blurb))
        f.write(body)
        f.write(TAIL)
    print("wrote", path)


if __name__ == "__main__":
    write("fig_minimalsupport",
          "Minimal support of a combination of natural objects at n = 4.",
          minimalsupport())
    write("fig_quarticloci",
          "Where the Weil classes of a quartic CM family are known to be "
          "algebraic.", quarticloci())
