#!/usr/bin/env python3
"""
make_more.py

Two more plates in three dimensions.

  fig_escape     the Boolean lattice of the three hypotheses of
                 Proposition 13.5, drawn as a solid cube: each vertex is a
                 subset, each edge adds one hypothesis, the shaded face is
                 where the divisor obstruction already binds on its own
  fig_lightcone  the null cone of a form of signature (3, b-3) in the slice
                 that carries the Kuga-Satake picture, with its rulings, the
                 hyperplane P, the line P-perp, and the point of square -1

Both use the painter's-algorithm renderer of render3d.py, so occlusion is
computed rather than drawn, and both place their labels with place.py, which
keeps every label outside the ink of the drawing and off every other label.
"""
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from render3d import Camera, Scene, addv, smul, sub, unit, cross
from place import Placer

HEAD = r"""%% {name}.tex   (generated by make_more.py; do not edit by hand)
%% {blurb}
\documentclass[tikz,border=8pt]{{standalone}}
\usepackage{{amsmath,amssymb}}
\usetikzlibrary{{arrows.meta,calc}}
\input{{palette}}
\begin{{document}}
\begin{{tikzpicture}}[x=1cm,y=1cm,line join=round,line cap=round,
  font=\small,text=PInk]
"""
TAIL = "\\end{tikzpicture}\n\\end{document}\n"


def write(name, blurb, sc, P):
    body = sc.emit()
    bad = P.check(body, sc.cam)
    if bad:
        raise SystemExit("placement failure in %s: %s" % (name, bad))
    labels = P.emit(body, sc.cam)
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, name + ".tex"), "w") as f:
        f.write(HEAD.format(name=name, blurb=blurb))
        f.write(body)
        f.write(labels)
        f.write(TAIL)
    print("%-18s %2d labels, clear of the ink and of each other"
          % (name, len(P.items)))


# =================================================================== escape
def fig_escape():
    """The eight positions a secant construction can occupy."""
    cam = Camera(eye=(7.4, -8.2, 5.0), target=(0.5, 0.5, 0.5), focal=9.0,
                 scale=4.40)
    sc, P = Scene(cam), Placer()

    def V(i, j, k):
        return (i * 1.0, j * 1.0, k * 1.0)

    # the face H1 = 1, shaded: the divisor obstruction already binds there
    sc.surface(lambda u, v: (1.0, u, v), (0, 1), (0, 1), 16, 16,
               base="PClay", opacity=0.42, ambient=0.40, diffuse=0.44)
    # the three faces meeting the origin, faintly, for solidity
    sc.surface(lambda u, v: (u, v, 0.0), (0, 1), (0, 1), 14, 14,
               base="PSlate", opacity=0.16, ambient=0.60, diffuse=0.30)
    sc.surface(lambda u, v: (u, 0.0, v), (0, 1), (0, 1), 14, 14,
               base="PSlate", opacity=0.16, ambient=0.60, diffuse=0.30)

    # the twelve edges
    for a in range(2):
        for b in range(2):
            sc.polyline([V(0, a, b), V(1, a, b)],
                        "PSlate,line width=0.9pt", priority=2)
            sc.polyline([V(a, 0, b), V(a, 1, b)],
                        "PSlate,line width=0.9pt", priority=2)
            sc.polyline([V(a, b, 0), V(a, b, 1)],
                        "PSlate,line width=0.9pt", priority=2)

    # the eight vertices
    for i in range(2):
        for j in range(2):
            for k in range(2):
                if (i, j, k) == (1, 1, 1):
                    st = ("circle,fill=PClay,draw=white,line width=0.7pt,"
                          "inner sep=3.0pt")
                elif (i, j, k) == (0, 0, 0):
                    st = ("circle,fill=PTeal,draw=white,line width=0.7pt,"
                          "inner sep=3.0pt")
                else:
                    st = ("circle,fill=white,draw=PSlate,line width=1.0pt,"
                          "inner sep=2.2pt")
                sc.dot3(V(i, j, k), st, priority=5)

    # the three generating directions, as arrows out of the origin
    for e, col in (((1, 0, 0), "PClay"), ((0, 1, 0), "PIndigo"),
                   ((0, 0, 1), "PGrass")):
        sc.polyline([V(0, 0, 0), smul(1.34, e)],
                    "%s,line width=1.15pt,-{Stealth[length=4pt]}" % col,
                    priority=3)

    P.add((1.42, 0, 0), r"(H1) $\ch$ in the divisor subring", "text=PClay",
          side="R")
    P.add((0, 1.42, 0), r"(H2) a $\Kx$-eigenclass", "text=PIndigo", side="R")
    P.add((0, 0, 1.42), r"(H3) a single line", "text=PGrass", side="L")
    P.add(V(1, 1, 1), r"all three hold", "text=PClay",
          side="R")
    P.add(V(0, 0, 0), r"none: Markman's case", "text=PTeal",
          side="L")
    P.add((1.0, 0.5, 0.5), r"(H1) alone already binds",
          "text=PClay", side="L")
    write("fig_escape",
          "The eight positions a secant construction can occupy, as the "
          "vertices of a cube.", sc, P)


# ================================================================ lightcone
def fig_lightcone():
    """The null cone of a form of signature (3, b-3), and the Kuga-Satake
    hyperplane inside it."""
    cam = Camera(eye=(7.8, -8.6, 4.4), target=(0.0, 0.0, 0.10), focal=9.2,
                 scale=3.30)
    sc, P = Scene(cam), Placer()

    R = 1.55

    def cone(t, r):
        return (r * math.cos(t), r * math.sin(t), r)

    def cone_dn(t, r):
        return (r * math.cos(t), r * math.sin(t), -r)

    sc.surface(lambda t, r: cone(t, r), (0, 2 * math.pi), (0.02, R),
               56, 14, base="PBlue", opacity=0.52, ambient=0.34,
               diffuse=0.52)
    sc.surface(lambda t, r: cone_dn(t, r), (0, 2 * math.pi), (0.02, R),
               56, 14, base="PBlue", opacity=0.52, ambient=0.34,
               diffuse=0.52)

    # rulings
    for m in range(24):
        t = 2 * math.pi * m / 24
        sc.curve(lambda r, t=t: cone(t, r), (0.0, R), 10,
                 "PTeal!70,line width=0.45pt", chunk=2)
        sc.curve(lambda r, t=t: cone_dn(t, r), (0.0, R), 10,
                 "PTeal!70,line width=0.45pt", chunk=2)

    # the hyperplane P = {z = 0}, on which q is positive definite
    sc.surface(lambda u, v: (u, v, 0.0), (-1.75, 1.75), (-1.75, 1.75),
               22, 22, base="PClay", opacity=0.30, ambient=0.56,
               diffuse=0.36)
    # the circle q = 1 inside it
    sc.curve(lambda t: (math.cos(t), math.sin(t), 0.0), (0, 2 * math.pi), 90,
             "PClay,line width=1.1pt", chunk=2)

    # the line P-perp and the point of square -1 on it
    sc.polyline([(0, 0, -1.95), (0, 0, 1.95)],
                "POchre,line width=1.2pt", priority=3)
    sc.dot3((0, 0, 1.0),
            "circle,fill=POchre,draw=white,line width=0.6pt,inner sep=2.3pt",
            priority=6)
    sc.dot3((0, 0, 0), "circle,fill=PInk,inner sep=1.5pt,draw=none",
            priority=6)

    P.add((1.30, 1.30, 0.0), r"$P=\{z=0\}$, where $q>0$", "text=PClay",
          side="R")
    P.add((0, 0, 1.92), r"$P^{\perp}$", "text=POchre", side="R")
    P.add((0, 0, 1.0), r"$q=-1$", "text=POchre", side="L")
    P.add((R * 0.72, -R * 0.72, R * 1.02), r"$q=0$, the null cone",
          "text=PBlue", side="R")
    P.add((0, 0, 0), r"$0$", "text=PInk", side="L")
    write("fig_lightcone",
          "The null cone of a form of signature (3, b-3), the hyperplane P "
          "on which q is positive, and the line P-perp.", sc, P)


if __name__ == "__main__":
    fig_escape()
    fig_lightcone()
