#!/usr/bin/env python3
"""
make_smooth.py

One plate for the smooth support theorem.

  fig_bmywindow   the two inequalities that bracket a smooth support, drawn
                  over the quarter plane of (b, d): the surface
                  3e(S) - K_S^2 = 24(b^4 - d^2), whose zero locus d = b^2 is
                  the Bogomolov-Miyaoka-Yau wall, the weaker wall d = 5b^2/3
                  where e(S) changes sign, and the four admissible lattice
                  points at b = 3

Nothing is drawn by eye.  The height of the surface at (b, d) is the actual
defect 24(b^4 - d^2) of the Bogomolov-Miyaoka-Yau inequality for the surface
that Theorem 14.118 attaches to the pair, scaled by a single constant so that
the drawing fits the frame, and the marked points are the four discriminants
of Corollary 14.119.
"""
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from render3d import Camera, Scene
from place import Placer

HEAD = r"""%% {name}.tex   (generated by make_smooth.py; do not edit by hand)
%% {blurb}
\documentclass[tikz,border=8pt]{{standalone}}
\usepackage{{amsmath,amssymb}}
\usetikzlibrary{{arrows.meta,calc}}
\input{{palette}}
\begin{{document}}
\begin{{tikzpicture}}[x=1cm,y=1cm,line join=round,line cap=round,
  font=\small,text=PInk]
"""
TAIL = "\\end{tikzpicture}\n\\end{document}\n"

BLO, BHI = 1.8, 4.2                 # range of b
DLO, DHI = 0.0, 22.0                # range of d
ZS = 1.0 / 8.5                      # one scale, after the cube root


def write(name, blurb, sc, P):
    body = sc.emit()
    bad = P.check(body, sc.cam)
    if bad:
        raise SystemExit("placement failure in %s: %s" % (name, bad))
    labels = P.emit(body, sc.cam)
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, name + ".tex"), "w") as f:
        f.write(HEAD.format(name=name, blurb=blurb))
        f.write(body)
        f.write(labels)
        f.write(TAIL)
    print("%-18s %2d labels, clear of the ink and of each other"
          % (name, len(P.items)))


def X(b):
    return 3.2 * (b - BLO) / (BHI - BLO) - 1.6


def Y(d):
    return 3.4 * (d - DLO) / (DHI - DLO) - 1.7


def defect(b, d):
    """the true defect, compressed by a signed cube root so that a range of
    four orders of magnitude fits one frame; the zero locus is untouched."""
    z = 24.0 * (b ** 4 - d * d)
    return math.copysign(abs(z) ** (1.0 / 3.0), z)


def pt(b, d, z=None):
    return (X(b), Y(d), ZS * (defect(b, d) if z is None else z))


def fig_bmywindow():
    cam = Camera(eye=(7.2, -8.0, 7.6), target=(0.0, 0.0, -0.10), focal=9.0,
                 scale=2.95)
    sc, P = Scene(cam), Placer()

    # the base plane, faint, to read the two walls against
    sc.surface(lambda b, d: (X(b), Y(d), 0.0), (BLO, BHI), (DLO, DHI),
               20, 22, base="PSlate", opacity=0.16, ambient=0.66,
               diffuse=0.26)

    # the defect surface, split at its zero locus so the two halves read
    sc.surface(lambda b, d: pt(b, d), (BLO, BHI), (DLO, DHI), 46, 52,
               base="PIndigo", opacity=0.58, ambient=0.34, diffuse=0.48,
               cull=lambda Q: sum(q[2] for q in Q) > 0)
    sc.surface(lambda b, d: pt(b, d), (BLO, BHI), (DLO, DHI), 46, 52,
               base="PClay", opacity=0.58, ambient=0.34, diffuse=0.48,
               cull=lambda Q: sum(q[2] for q in Q) <= 0)

    # the two walls, drawn on the base plane
    sc.curve(lambda b: (X(b), Y(min(DHI, b * b)), 0.0), (BLO, BHI), 90,
             "PMag,line width=1.35pt", chunk=2)
    sc.curve(lambda b: (X(b), Y(min(DHI, 5 * b * b / 3.0)), 0.0),
             (BLO, BHI), 90,
             "PGrass,line width=1.0pt,dash pattern=on 2.6pt off 2.2pt",
             chunk=2)
    # and the zero curve lifted onto the surface, which is the same curve
    sc.curve(lambda b: pt(b, min(DHI, b * b), 0.0), (BLO, BHI), 90,
             "PMag!70,line width=0.7pt", chunk=2)

    # the line b = 3, and the four admissible discriminants on it
    sc.polyline([pt(3.0, DLO, 0.0), pt(3.0, DHI, 0.0)],
                "PInk!60,line width=0.7pt,dash pattern=on 1.6pt off 1.6pt",
                priority=2)
    for d in (1, 3, 5, 7):
        sc.polyline([pt(3.0, d, 0.0), pt(3.0, d)],
                    "PAmber,line width=0.7pt", priority=3)
        sc.dot3(pt(3.0, d),
                "circle,fill=PAmber,draw=white,line width=0.6pt,inner sep=2.2pt",
                priority=6)
    for d in (11, 13, 15):
        sc.dot3(pt(3.0, d),
                "circle,draw=PClay,line width=0.9pt,fill=white,inner sep=1.7pt",
                priority=6)
    sc.dot3(pt(3.0, 9.0, 0.0),
            "circle,fill=PMag,draw=white,line width=0.6pt,inner sep=2.0pt",
            priority=6)

    P.add(pt(BLO, DHI), r"$3e-K^{2}=24(b^{4}-d^{2})$", "text=PIndigo",
          side="L")
    P.add((X(BHI), Y(min(DHI, BHI * BHI)), 0.0), r"$d=b^{2}$, the wall",
          "text=PMag", side="R")
    P.add((X(3.4), Y(min(DHI, 5 * 3.4 * 3.4 / 3.0)), 0.0),
          r"$d=\tfrac53 b^{2}$, where $e=0$", "text=PGrass", side="R")
    P.add(pt(3.0, 3), r"$d=1,3,5,7$", "text=PAmber", side="L")
    P.add(pt(3.0, 9.0, 0.0), r"$d=9$: equality", "text=PMag", side="R")
    P.add(pt(3.0, 13), r"excluded", "text=PClay", side="R")
    P.add((X(BHI), Y(DLO), 0.0), r"$b$", "text=PSlate", side="R")
    P.add((X(BLO), Y(DHI), 0.0), r"$d$", "text=PSlate", side="L")
    write("fig_bmywindow",
          "The Bogomolov-Miyaoka-Yau defect of a smooth support over the "
          "quarter plane of (b,d), and the four admissible discriminants.",
          sc, P)


if __name__ == "__main__":
    fig_bmywindow()
