#!/usr/bin/env python3
"""
make_core.py

Figures 1 to 5, rebuilt in three dimensions from their own data.  Nothing
here is drawn by eye: the tesseract is the real 4-cube projected, the bar
heights are the dimensions the paper computes, and the orbit is the actual
image of K^x acting by tau^{2n}.  Shading is Lambert, the draw order is by
depth, and labels are placed outside the ink by place.py with leaders, so no
label can touch the drawing or another label.

  fig_weilcube      the 2^{2n} monomials w(T) as the vertices of the 4-cube,
                    projected, with the bipartition by |T| mod 2 that splits
                    the Weil line into its two generators
  fig_hodgespike    dim Hdg^k(A) over the two axes k and n, as a solid bar
                    field: one everywhere except the middle degree, three there
  fig_charactergrid the K^x-grading of H^{2n}, the summand at (r,s) having
                    dimension C(2n,r)C(2n,s), with the two cells that carry the
                    Weil line and the one that carries eta^n marked
  fig_chernline     the Weil line as a plane, the orbit of K^x inside it, and
                    the transverse axis carrying eta^n
  fig_annihilator   H^{0,2} in its three blocks, of dimensions C(n,2), n^2 and
                    C(n,2), with the middle one carried to zero by the class
"""
import math
import os
import sys
from itertools import combinations

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from render3d import Camera, Scene, addv, smul, sub, unit, cross
from place import Placer

HEAD = r"""%% {name}.tex   (generated by make_core.py; do not edit by hand)
%% {blurb}
\documentclass[tikz,border=8pt]{{standalone}}
\usepackage{{amsmath,amssymb}}
\usetikzlibrary{{arrows.meta,calc}}
\input{{palette}}
\begin{{document}}
\begin{{tikzpicture}}[x=1cm,y=1cm,line join=round,line cap=round,
  font=\small,text=PInk]
"""
TAIL = "\\end{tikzpicture}\n\\end{document}\n"


def write(name, blurb, sc, P):
    body = sc.emit()
    bad = P.check(body, sc.cam)
    if bad:
        raise SystemExit("placement failure in %s: %s" % (name, bad))
    labels = P.emit(body, sc.cam)
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, name + ".tex"), "w") as f:
        f.write(HEAD.format(name=name, blurb=blurb))
        f.write(body)
        f.write(labels)
        f.write(TAIL)
    print("%-18s %2d labels, clear of the ink and of each other"
          % (name, len(P.items)))


def binom(n, k):
    if k < 0 or k > n:
        return 0
    r = 1
    for i in range(k):
        r = r * (n - i) // (i + 1)
    return r


def box(sc, x0, y0, z0, dx, dy, dz, base, op=0.86, edge=True):
    """An axis-aligned solid, six faces, depth sorted by the renderer."""
    faces = [
        (lambda u, v: (x0 + dx * u, y0 + dy * v, z0)),
        (lambda u, v: (x0 + dx * u, y0 + dy * v, z0 + dz)),
        (lambda u, v: (x0, y0 + dy * u, z0 + dz * v)),
        (lambda u, v: (x0 + dx, y0 + dy * u, z0 + dz * v)),
        (lambda u, v: (x0 + dx * u, y0, z0 + dz * v)),
        (lambda u, v: (x0 + dx * u, y0 + dy, z0 + dz * v)),
    ]
    for f in faces:
        sc.surface(f, (0, 1), (0, 1), 1, 1, base=base, opacity=op,
                   ambient=0.42, diffuse=0.54, edge=edge)


# ===================================================================== 1
def fig_weilcube():
    """The 4-cube, projected, coloured by the parity of |T|."""
    cam = Camera(eye=(7.2, -7.8, 4.6), target=(0, 0, 0.0), focal=8.6,
                 scale=2.05)
    sc, P = Scene(cam), Placer()

    # a standard projection of {0,1}^4 into R^3: the fourth axis goes to a
    # short diagonal, which is what makes the two cubes visibly nested
    E = [(1.55, 0.0, 0.0), (0.0, 1.55, 0.0), (0.0, 0.0, 1.55),
         (0.62, 0.62, 0.58)]

    def pt(T):
        p = (0.0, 0.0, 0.0)
        for i in range(4):
            if T & (1 << i):
                p = addv(p, E[i])
        return addv(p, (-1.08, -1.08, -1.06))

    for a in range(16):
        for i in range(4):
            b = a | (1 << i)
            if b != a:
                even = bin(a).count("1") % 2 == 0
                sc.polyline([pt(a), pt(b)],
                            "%s,line width=0.55pt,opacity=0.55"
                            % ("PIndigo" if even else "PMag"))
    for a in range(16):
        even = bin(a).count("1") % 2 == 0
        sc.dot3(pt(a),
                "circle,fill=%s,draw=white,line width=0.55pt,inner sep=2.1pt"
                % ("PIndigo" if even else "PMag"), priority=4)

    P.add(pt(0), r"$T=\emptyset$", "text=PIndigo", side="L")
    P.add(pt(15), r"$T=\{1,2,3,4\}$", "text=PIndigo", side="R")
    P.add(pt(1), r"$|T|$ odd: $\omega_{2}$", "text=PMag", side="L")
    P.add(pt(3), r"$|T|$ even: $\omega_{1}$", "text=PIndigo", side="R")
    P.add(pt(7), r"$2^{2n}=16$ monomials $w(T)$", "text=PSlate", side="R")
    write("fig_weilcube",
          "The 4-cube of monomials w(T), with the bipartition by the parity "
          "of |T| that separates the two generators of the Weil line.",
          sc, P)


# ===================================================================== 2
def fig_hodgespike():
    """dim Hdg^k(A) as a bar field over k and n."""
    cam = Camera(eye=(8.6, -8.2, 5.4), target=(1.9, 1.0, 0.45), focal=9.0,
                 scale=1.95)
    sc, P = Scene(cam), Placer()

    W, D, HS = 0.34, 0.40, 0.42
    cols = {2: "PIndigo", 3: "PTeal", 4: "PViolet"}
    for j, n in enumerate((2, 3, 4)):
        for k in range(0, 2 * n + 1):
            h = 3 if k == n else 1
            box(sc, k * 0.46, j * 0.62, 0.0, W, D, h * HS,
                cols[n] if k != n else "PAmber",
                op=0.92 if k == n else 0.80)

    sc.polyline([(-0.22, -0.18, 0), (4.15, -0.18, 0)],
                "PInk,line width=0.6pt,-{Stealth[length=3.6pt]}")
    sc.polyline([(-0.22, -0.18, 0), (-0.22, 1.82, 0)],
                "PInk,line width=0.6pt,-{Stealth[length=3.6pt]}")
    sc.polyline([(-0.22, -0.18, 0), (-0.22, -0.18, 1.55)],
                "PInk,line width=0.6pt,-{Stealth[length=3.6pt]}")

    P.add((4.15, -0.18, 0), r"$k$", side="R")
    P.add((-0.22, 1.82, 0), r"$n=2,3,4$", side="L")
    P.add((-0.22, -0.18, 1.55), r"$\dim_{\QQ}\Hdg^{k}(A)$", side="L")
    P.add((2 * 0.46, 0.62, 3 * HS), r"$k=n$: $\QQ\eta^{n}\oplus W(A)$",
          "text=PAmber", side="R")
    P.add((5 * 0.46, 1.24, HS), r"one class $\eta^{k}$ elsewhere",
          "text=PViolet", side="R")
    write("fig_hodgespike",
          "The dimensions of Hdg^k(A) over k and n: one everywhere except "
          "the middle degree, three there.",
          sc, P)


# ===================================================================== 3
def fig_charactergrid():
    """The summand at (r,s) of H^{2n}, with its true dimension as height."""
    cam = Camera(eye=(8.4, -8.6, 5.6), target=(1.5, 0.0, 0.55), focal=9.0,
                 scale=2.30)
    sc, P = Scene(cam), Placer()

    n = 3
    dims = [binom(2 * n, r) * binom(2 * n, 2 * n - r) for r in range(2 * n + 1)]
    top = max(dims)
    for r, d in enumerate(dims):
        h = 1.55 * (d / top) ** 0.55
        if r in (0, 2 * n):
            col = "PMag"
        elif r == n:
            col = "PAmber"
        else:
            col = "PIndigo"
        box(sc, r * 0.52, 0.0, 0.0, 0.38, 0.46, max(h, 0.05), col,
            op=0.90)

    sc.polyline([(-0.20, -0.16, 0), (3.50, -0.16, 0)],
                "PInk,line width=0.6pt,-{Stealth[length=3.6pt]}")
    sc.polyline([(-0.20, -0.16, 0), (-0.20, -0.16, 1.80)],
                "PInk,line width=0.6pt,-{Stealth[length=3.6pt]}")

    P.add((3.50, -0.16, 0), r"$r$, with $s=2n-r$", side="R")
    P.add((-0.20, -0.16, 1.80),
          r"$\dim\bigl(\bigwedge^{r}V_{+}\otimes\bigwedge^{s}V_{-}\bigr)$",
          side="L")
    P.add((0.0, 0.23, 0.30), r"$(2n,0)$ and $(0,2n)$: the Weil line",
          "text=PMag", side="L")
    P.add((n * 0.52, 0.23, 1.55), r"$(n,n)$: $\eta^{n}$ lives here",
          "text=PAmber", side="R")
    P.add((5 * 0.52, 0.23, 0.95), r"$\binom{6}{r}\binom{6}{6-r}$, summing to "
                                  r"$\binom{12}{6}=924$", "text=PIndigo",
          side="R")
    write("fig_charactergrid",
          "The K-grading of H^{2n} at n = 3: the summand at (r,s) with its "
          "true dimension, and the three cells that matter.",
          sc, P)


# ===================================================================== 4
def fig_chernline():
    """The Weil line as a plane, the orbit inside it, the transverse axis."""
    cam = Camera(eye=(7.0, -7.6, 4.4), target=(0, 0, 0.15), focal=8.6,
                 scale=2.35)
    sc, P = Scene(cam), Placer()

    sc.surface(lambda u, v: (1.65 * u, 1.65 * v, 0.0), (-1, 1), (-1, 1),
               22, 22, base="PIndigo", opacity=0.32, ambient=0.54,
               diffuse=0.42)

    # the orbit of K^x on the plane: tau^{2n} acting as a rotation-scaling
    sc.curve(lambda t: (1.18 * math.exp(0.10 * t) * math.cos(t),
                        1.18 * math.exp(0.10 * t) * math.sin(t), 0.0),
             (-2.6, 1.05), 200, "PMag,line width=1.15pt", chunk=2)
    for t in (-2.2, -1.1, 0.0, 0.9):
        r = 1.18 * math.exp(0.10 * t)
        sc.dot3((r * math.cos(t), r * math.sin(t), 0.0),
                "circle,fill=PMag,draw=white,line width=0.5pt,inner sep=1.9pt",
                priority=4)

    sc.polyline([(0, 0, -1.30), (0, 0, 1.55)],
                "PAmber,line width=1.15pt,-{Stealth[length=4pt]}")
    sc.dot3((0, 0, 0.95),
            "circle,fill=PAmber,draw=white,line width=0.5pt,inner sep=1.9pt",
            priority=4)
    sc.dot3((0, 0, 0), "circle,fill=PInk,inner sep=1.4pt,draw=none",
            priority=4)

    P.add((1.65, 1.10, 0.0), r"$W(A)$, a plane", "text=PIndigo", side="R")
    P.add((1.30, -0.35, 0.0), r"the $\Kx$-orbit: $\tau^{2n}$", "text=PMag",
          side="R")
    P.add((0, 0, 1.30), r"$\QQ\eta^{n}$, the norm character", "text=PAmber",
          side="R")
    P.add((-1.20, -1.10, 0.0), r"no $\Kx$-stable line inside $W(A)$",
          "text=PSlate", side="L")
    write("fig_chernline",
          "The Weil line is a plane and the orbit of K^x spans it; eta^n "
          "sits on a transverse axis with a different character.",
          sc, P)


# ===================================================================== 5
def fig_annihilator():
    """H^{0,2} in three blocks, the middle one carried to zero."""
    cam = Camera(eye=(8.0, -8.4, 4.8), target=(0.55, 0.0, 0.42), focal=8.8,
                 scale=2.25)
    sc, P = Scene(cam), Placer()

    n = 3
    blocks = [(binom(n, 2), "PIndigo", r"\bigwedge^{2}V_{+}^{0,1}"),
              (n * n, "PAmber", r"V_{+}^{0,1}\otimes V_{-}^{0,1}"),
              (binom(n, 2), "PMag", r"\bigwedge^{2}V_{-}^{0,1}")]
    z = 0.0
    tops = []
    for d, col, lab in blocks:
        h = 0.20 + 0.105 * d
        box(sc, 0.0, 0.0, z, 0.92, 0.72, h, col, op=0.88)
        tops.append((z + h / 2, d, col, lab))
        z += h + 0.085

    # the image side: the two outer blocks survive, the middle goes to zero
    sc.polyline([(1.15, 0.36, tops[0][0]), (2.15, 0.36, tops[0][0])],
                "PIndigo,line width=0.9pt,-{Stealth[length=4pt]}")
    sc.polyline([(1.15, 0.36, tops[2][0]), (2.15, 0.36, tops[2][0])],
                "PMag,line width=0.9pt,-{Stealth[length=4pt]}")
    sc.polyline([(1.15, 0.36, tops[1][0]), (2.15, 0.36, tops[1][0])],
                "PAmber,line width=0.9pt,-{Stealth[length=4pt]}")
    box(sc, 2.25, 0.10, tops[0][0] - 0.16, 0.42, 0.52, 0.32, "PIndigo",
        op=0.88)
    box(sc, 2.25, 0.10, tops[2][0] - 0.16, 0.42, 0.52, 0.32, "PMag", op=0.88)
    sc.dot3((2.46, 0.36, tops[1][0]),
            "circle,fill=PAmber,draw=white,line width=0.5pt,inner sep=2.2pt",
            priority=4)

    P.add((0.46, 0.36, tops[0][0]), r"$\binom{n}{2}=3$", "text=PIndigo",
          side="L")
    P.add((0.46, 0.36, tops[1][0]), r"$n^{2}=9$, the mixed block",
          "text=PAmber", side="L")
    P.add((0.46, 0.36, tops[2][0]), r"$\binom{n}{2}=3$", "text=PMag",
          side="L")
    P.add((2.46, 0.36, tops[1][0]), r"$0$", "text=PAmber", side="R")
    P.add((2.46, 0.36, tops[0][0]), r"injective", "text=PIndigo", side="R")
    P.add((1.65, 0.36, tops[2][0] + 0.55), r"$z\mapsto z\cdot\omega$",
          "text=PSlate", side="R")
    write("fig_annihilator",
          "H^{0,2} in three blocks at n = 3: the outer two are carried "
          "injectively, the middle one of dimension n^2 goes to zero.",
          sc, P)


if __name__ == "__main__":
    fig_weilcube()
    fig_hodgespike()
    fig_charactergrid()
    fig_chernline()
    fig_annihilator()
    print("five plates written")
