#!/usr/bin/env python3
"""fig_properness.tex: a shaded perspective render of the period domain as a
ball sliced by the closed strata of the algebraic locus.  One stratum carries
the base point supplied by the quaternionic construction; a very general point
sits in the gap between two strata."""

import math
from render3d import Camera, Scene, unit, dot, cross

HEAD = r"""%% fig_properness.tex   (generated by make_properness.py)
%% The bounded period domain, the closed strata of the algebraic locus inside
%% it, the base point on one stratum and a very general point off all of them.
\documentclass[tikz,border=6pt]{standalone}
\usepackage{amsmath,amssymb}
\usetikzlibrary{arrows.meta,calc}
\input{palette}
\begin{document}
\begin{tikzpicture}[x=1cm,y=1cm,line join=round,line cap=round,
  font=\small,text=PInk]
"""
TAIL = "\\end{tikzpicture}\n\\end{document}\n"

R = 1.0                                  # radius of the ball
WARP = 0.085                              # how far each stratum bends
# height, rotation of the warp, and whether this is the base stratum
STRATA = [(-0.72, 0.00), (-0.40, 0.90), (-0.06, 1.80),
          (0.30, 2.60), (0.66, 0.50)]
BASE = 1                                 # index of the highlighted stratum


def radius_at(c):
    return 0.78 * math.sqrt(max(0.0, R * R - c * c))


def stratum(c, th):
    rmax = radius_at(c)

    def f(t, phi):
        r = rmax * t
        x, y = r * math.cos(phi), r * math.sin(phi)
        u = x * math.cos(th) - y * math.sin(th)
        v = x * math.sin(th) + y * math.cos(th)
        return (x, y, c + WARP * (u * u - v * v))
    return f


def main():
    cam = Camera(eye=(3.95, -6.35, 3.15), target=(0, 0, 0.0),
                 up=(0, 0, 1), focal=7.4, scale=2.05)
    sc = Scene(cam, light=(0.30, -0.78, 0.88))

    for k, (c, th) in enumerate(STRATA):
        col = "PClay" if k == BASE else "PBlue"
        sc.surface(stratum(c, th), (0.02, 1.0), (0.0, 2 * math.pi), 12, 72,
                   base=col, ambient=0.40 if col == "PBlue" else 0.46,
                   diffuse=0.52)
        # the rim of each stratum, so the stack is countable by eye
        rim = stratum(c, th)
        sc.curve(lambda a, g=rim: g(1.0, a), (0, 2 * math.pi), 180,
                 ("%s,line width=0.55pt,opacity=0.85" % col), priority=1,
                 chunk=3)

    body = sc.emit()
    out = [body]

    # the silhouette of the ball: the circle {P : P . eye = R^2} on the sphere
    e = cam.eye
    ne = math.sqrt(dot(e, e))
    u = unit(e)
    h = R * R / ne
    rr = math.sqrt(max(0.0, R * R - h * h))
    b1 = unit(cross(u, (0.0, 0.0, 1.0)))
    b2 = cross(u, b1)
    pts = []
    for k in range(241):
        t = 2 * math.pi * k / 240
        P = tuple(h * u[i] + rr * (math.cos(t) * b1[i] + math.sin(t) * b2[i])
                  for i in range(3))
        pts.append(cam.project(P)[0])
    out.append("  \\draw[PSlate,line width=0.9pt,opacity=0.85] %s -- cycle;\n"
               % " -- ".join("(%.4f,%.4f)" % q for q in pts))

    # the two marked points, drawn over everything
    cB, thB = STRATA[BASE]
    s0 = stratum(cB, thB)(0.62, -0.70)
    sg = (0.60, 0.66, 0.10)

    def marker(P, style):
        (x, y), _ = cam.project(P)
        out.append("  \\node[%s] at (%.4f,%.4f) {};\n" % (style, x, y))
        return (x, y)

    x0, y0 = marker(s0, "circle,draw=PClay,fill=white,line width=1.3pt,"
                        "inner sep=2.1pt")
    x1, y1 = marker(sg, "circle,draw=PInk,fill=PInk,inner sep=1.5pt")

    def lead(x, y, dx, dy, text, col, anchor):
        sx = 0.13 if dx > 0 else -0.13
        sy = 0.13 if dy > 0 else -0.13
        out.append("  \\draw[%s,line width=0.5pt] (%.3f,%.3f) -- (%.3f,%.3f);\n"
                   % (col, x + sx, y + sy, x + dx, y + dy))
        out.append("  \\node[anchor=%s,text=%s] at (%.3f,%.3f) {%s};\n"
                   % (anchor, col, x + dx + (0.09 if anchor == "west"
                                             else -0.09), y + dy, text))

    lead(x0, y0, -1.60, -1.25, "$s_{0}$", "PClay", "east")
    lead(x1, y1, 1.45, 0.95, "$s$, very general", "PInk", "west")

    # the domain label, just outside the silhouette at the lower right
    lx, ly = max(pts, key=lambda q: q[0] - 1.25 * q[1])
    out.append("  \\node[anchor=north west,text=PSlate] at (%.3f,%.3f) "
               "{$\\cD_{n,n}$};\n" % (lx + 0.06, ly - 0.06))

    # key
    kx, ky = -3.30, 2.42
    for dy, col, txt in ((0.00, "PBlue",
                          "$\\Sigma_{\\underline{P},\\underline{q}}$, "
                          "closed"),
                         (-0.50, "PClay", "the stratum through $s_{0}$")):
        out.append("  \\draw[%s,line width=2.8pt,opacity=0.60] "
                   "(%.2f,%.2f) -- (%.2f,%.2f);\n"
                   % (col, kx, ky + dy, kx + 0.50, ky + dy))
        out.append("  \\node[anchor=west,text=%s,font=\\footnotesize] "
                   "at (%.2f,%.2f) {%s};\n" % (col, kx + 0.61, ky + dy, txt))

    open("fig_properness.tex", "w").write(HEAD + "".join(out) + TAIL)
    print("wrote fig_properness.tex")


if __name__ == "__main__":
    main()
