#!/usr/bin/env python3
"""fig_spinor.tex: a shaded perspective render of the smooth quadric that the
even spinor variety is in the smallest case, with the front halves of both
rulings and the rational secant line meeting it in two conjugate points."""

import math
from render3d import Camera, Scene, unit, dot, sub

HEAD = r"""%% fig_spinor.tex   (generated by make_spinor.py)
%% Perspective render of the quadric x^2 + y^2 - z^2 = 1, meshed and Lambert
%% shaded.  Only the camera-facing halves of the rulings are drawn, so no line
%% fights the mesh for depth, and the secant line P_t is drawn over the whole.
\documentclass[tikz,border=6pt]{standalone}
\usepackage{amsmath,amssymb}
\usetikzlibrary{arrows.meta,calc}
\input{palette}
\begin{document}
\begin{tikzpicture}[x=1cm,y=1cm,line join=round,line cap=round,
  font=\small,text=PInk]
"""
TAIL = "\\end{tikzpicture}\n\\end{document}\n"

T = 1.28


def S(t, th):
    return (math.cosh(t) * math.cos(th), math.cosh(t) * math.sin(th),
            math.sinh(t))


def nrm(p):
    return unit((p[0], p[1], -p[2]))


def ruling(th, s):
    def g(u):
        return (math.cos(th) - s * u * math.sin(th),
                math.sin(th) + s * u * math.cos(th), u)
    return g


def main():
    cam = Camera(eye=(6.0, -7.8, 4.1), target=(0, 0, 0.02),
                 up=(0, 0, 1), focal=7.4, scale=1.42)
    sc = Scene(cam, light=(0.30, -0.82, 0.82))

    sc.surface(S, (-T, T), (0.0, 2 * math.pi), 28, 80,
               base="PBlue", ambient=0.46, diffuse=0.54)
    body = sc.emit()

    out = [body]

    # front halves of the two rulings, drawn over the shaded surface
    NR = 22
    for k in range(NR):
        th = 2 * math.pi * k / NR
        for s, col, op in ((+1, "PTeal", 0.92), (-1, "POchre", 0.92)):
            for run in sc.front_runs(ruling(th, s), nrm, (-T, T), 48):
                pr = [cam.project(p)[0] for p in run]
                out.append("  \\draw[%s,line width=0.55pt,opacity=%.2f] %s;\n"
                           % (col, op,
                              " -- ".join("(%.4f,%.4f)" % q for q in pr)))

    # the waist circle, front half only
    for run in sc.front_runs(lambda a: S(0.0, a), nrm, (0, 2 * math.pi), 160):
        pr = [cam.project(p)[0] for p in run]
        out.append("  \\draw[PInk,line width=0.7pt,opacity=0.5] %s;\n"
                   % " -- ".join("(%.4f,%.4f)" % q for q in pr))

    # the rational secant line
    th0, u0 = 0.86, 0.95
    A = ruling(th0, +1)(+u0)
    B = ruling(th0, +1)(-u0)

    def chord(t):
        return tuple(A[i] + (B[i] - A[i]) * t for i in range(3))

    pr = [cam.project(chord(-0.40 + 1.80 * k / 60))[0] for k in range(61)]
    out.append("  \\draw[PClay,line width=1.6pt] %s;\n"
               % " -- ".join("(%.4f,%.4f)" % q for q in pr))
    for P in (A, B):
        (x, y), _ = cam.project(P)
        out.append("  \\node[circle,draw=PClay,fill=white,line width=1.2pt,"
                   "inner sep=2.1pt] at (%.4f,%.4f) {};\n" % (x, y))

    (ax, ay), _ = cam.project(A)
    (bx, by), _ = cam.project(B)
    (ex, ey), _ = cam.project(chord(1.40))
    out.append("  \\draw[PClay,line width=0.5pt] (%.3f,%.3f) -- (%.3f,%.3f);\n"
               % (ax + 0.18, ay + 0.12, ax + 1.35, ay + 0.86))
    out.append("  \\node[anchor=west,text=PClay] at (%.3f,%.3f) "
               "{$[e^{+st}]$};\n" % (ax + 1.40, ay + 0.88))
    out.append("  \\draw[PClay,line width=0.5pt] (%.3f,%.3f) -- (%.3f,%.3f);\n"
               % (bx + 0.18, by - 0.12, bx + 1.35, by - 0.60))
    out.append("  \\node[anchor=west,text=PClay] at (%.3f,%.3f) "
               "{$[e^{-st}]$};\n" % (bx + 1.40, by - 0.62))
    out.append("  \\node[anchor=north west,text=PClay] at (%.3f,%.3f) "
               "{$P_{t}$};\n" % (ex + 0.06, ey - 0.02))

    # key
    x0, y0 = -4.75, 2.95
    for dy, col, txt in ((0.00, "PTeal", "$\\{[e^{sv}]\\}$, one ruling"),
                         (-0.55, "POchre", "$\\{[e^{-sv}]\\}$, the other"),
                         (-1.10, "PClay",
                          "$P_{t}$, defined over $\\QQ$")):
        out.append("  \\draw[%s,line width=1.2pt] (%.2f,%.2f) -- (%.2f,%.2f);\n"
                   % (col, x0, y0 + dy, x0 + 0.55, y0 + dy))
        out.append("  \\node[anchor=west,text=%s,font=\\footnotesize] "
                   "at (%.2f,%.2f) {%s};\n" % (col, x0 + 0.66, y0 + dy, txt))

    open("fig_spinor.tex", "w").write(HEAD + "".join(out) + TAIL)
    print("wrote fig_spinor.tex")


if __name__ == "__main__":
    main()
