#!/usr/bin/env python3
"""
make_closure.py

One plate for the closure theorem.

  fig_closure    the implication graph of the scope section drawn as a stack
                 of plates, one per level of the derivation.  Each statement is
                 a small solid on the plate of its level, coloured by its
                 standing: indigo for statements derived by the rules, clay
                 for open statements, grass for what the paper proves.  The
                 spine of derived statements runs up the middle; the two
                 statements (F2) and (F3), each the conjecture for a class of
                 Hodge classes no Weil line reaches, enter from the right at the
                 level where each is needed; the propagation statement (P2)
                 enters from below and reaches both discriminant cases of the
                 quadratic fields and the fields of higher degree, fed by the
                 base points of every family.  Under (P2) stand three pillars,
                 the three constraints proved on any object that meets it.
                 The secant route reaches the trivial discriminant and is
                 crossed out before the other; the bounded criterion (P1) is
                 drawn apart, closed on itself, because it is equivalent to
                 its own conclusion.

The nodes, the levels and the edges are those of the rule set that
closure_graph.py carries; the level of a node is its height in the
topological order of that rule set.
"""
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from render3d import Camera, Scene
from place import Placer

HEAD = r"""%% {name}.tex   (generated by make_closure.py; do not edit by hand)
%% {blurb}
\documentclass[tikz,border=8pt]{{standalone}}
\usepackage{{amsmath,amssymb}}
\usetikzlibrary{{arrows.meta,calc}}
\input{{palette}}
\begin{{document}}
\begin{{tikzpicture}}[x=1cm,y=1cm,line join=round,line cap=round,
  font=\small,text=PInk]
"""
TAIL = "\\end{tikzpicture}\n\\end{document}\n"

# name: (x, y, level, standing)   d derived, o open, p proved, s restatement
NODES = {
    "HC":       (0.10, 0.10, 5, "d"),
    "HC_ab":    (-0.45, 0.05, 4, "d"),
    "F3":       (2.55, 1.05, 4, "o"),
    "weil_all": (-1.00, 0.00, 3, "d"),
    "F2":       (2.40, 1.15, 3, "o"),
    "weil_iq":  (-1.95, -0.35, 2, "d"),
    "weil_cm":  (0.55, 0.65, 2, "d"),
    "triv":     (-2.95, -0.95, 1, "d"),
    "nontriv":  (-1.25, 0.35, 1, "d"),
    "P2":       (-1.35, -2.15, 0, "o"),
    "base":     (-3.85, -0.55, 0, "p"),
    "secant":   (1.95, -1.55, 0, "o"),
    "P1":       (3.55, -2.85, 0, "s"),
}

EDGES = [
    ("HC_ab", "HC", "spine"), ("F3", "HC", "open"),
    ("weil_all", "HC_ab", "spine"), ("F2", "HC_ab", "open"),
    ("weil_iq", "weil_all", "spine"), ("weil_cm", "weil_all", "spine"),
    ("triv", "weil_iq", "spine"), ("nontriv", "weil_iq", "spine"),
    ("P2", "triv", "prop"), ("P2", "nontriv", "prop"), ("P2", "weil_cm", "prop"),
    ("base", "triv", "base"), ("base", "nontriv", "base"),
    ("base", "weil_cm", "base"),
    ("secant", "triv", "stop"),
]

COL = {"d": "PIndigo", "o": "PClay", "p": "PGrass", "s": "PSlate"}
ZS = 0.82
Z0 = -1.70


def pos(n):
    x, y, lv, _ = NODES[n]
    return (x, y, ZS * lv + Z0)


def top(n):
    x, y, z = pos(n)
    return (x, y, z + 0.075)


def write(name, blurb, sc, P):
    body = sc.emit()
    bad = P.check(body, sc.cam)
    if bad:
        raise SystemExit("placement failure in %s: %s" % (name, bad))
    labels = P.emit(body, sc.cam)
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, name + ".tex"), "w") as f:
        f.write(HEAD.format(name=name, blurb=blurb))
        f.write(body)
        f.write(labels)
        f.write(TAIL)
    print("%-18s %2d labels, clear of the ink and of each other"
          % (name, len(P.items)))


def fig_closure():
    cam = Camera(eye=(8.2, -9.4, 6.0), target=(-0.35, -0.30, 0.15),
                 focal=10.2, scale=2.30)
    sc, P = Scene(cam), Placer()

    # the plates, one per level, with a fine grid ruled on each
    for lv in range(0, 6):
        on = [n for n in NODES if NODES[n][2] == lv]
        xs = [NODES[n][0] for n in on]
        ys = [NODES[n][1] for n in on]
        cx, cy = 0.5 * (min(xs) + max(xs)), 0.5 * (min(ys) + max(ys))
        hx = max(1.25, 0.5 * (max(xs) - min(xs)) + 0.62)
        hy = max(0.85, 0.5 * (max(ys) - min(ys)) + 0.58)
        x0, x1, y0, y1 = cx - hx, cx + hx, cy - hy, cy + hy
        z = ZS * lv + Z0
        sc.surface(lambda u, v, z=z: (u, v, z), (x0, x1), (y0, y1), 8, 6,
                   base="PSlate", opacity=0.12, ambient=0.72, diffuse=0.18)
        sc.polyline([(x0, y0, z), (x1, y0, z), (x1, y1, z), (x0, y1, z),
                     (x0, y0, z)], "PRule,line width=0.40pt", priority=1)
        steps = 6
        for k in range(1, steps):
            t = k / steps
            sc.polyline([(x0 + t * (x1 - x0), y0, z), (x0 + t * (x1 - x0), y1, z)],
                        "PRule!45,line width=0.15pt", priority=1)
            sc.polyline([(x0, y0 + t * (y1 - y0), z), (x1, y0 + t * (y1 - y0), z)],
                        "PRule!45,line width=0.15pt", priority=1)
        # the level index on the near corner
        sc.dot3((x1, y0, z), "circle,fill=PRule,inner sep=0.9pt", priority=2)

    styles = {
        "spine": "PIndigo,line width=1.45pt",
        "open": "PClay,line width=1.10pt,dash pattern=on 3pt off 2pt",
        "prop": "PGrass,line width=1.30pt",
        "base": "PGrass!70!PSlate,line width=0.70pt,dash pattern=on 1.4pt off 1.6pt",
        "stop": "PClay,line width=1.10pt,dash pattern=on 3pt off 2pt",
    }
    for a, b, kind in EDGES:
        pa, pb = top(a), pos(b)
        mid = (0.5 * (pa[0] + pb[0]), 0.5 * (pa[1] + pb[1]),
               0.5 * (pa[2] + pb[2]) + 0.14)
        q = (0.12 * mid[0] + 0.88 * pb[0], 0.12 * mid[1] + 0.88 * pb[1],
             0.12 * mid[2] + 0.88 * pb[2] - 0.02)
        sc.arrow([pa, mid, q], styles[kind], priority=3)

    # drop lines from every node to the ground plate, to read the levels
    for n, (x, y, lv, st) in NODES.items():
        if lv > 0:
            sc.polyline([(x, y, Z0), (x, y, ZS * lv + Z0)],
                        "PRule!70,line width=0.25pt,dash pattern=on 0.8pt off 1.4pt",
                        priority=1)

    # the nodes, as small solids
    for n, (x, y, lv, st) in NODES.items():
        p = pos(n)
        sc.box((p[0], p[1], p[2] + 0.04), (0.36, 0.26, 0.10), base=COL[st],
               opacity=0.88, ambient=0.46, diffuse=0.44,
               edge_style="%s!80!black,line width=0.35pt" % COL[st])

    # three pillars under the propagation statement: the constraints on any
    # object that meets it
    px, py, pz = pos("P2")
    pillars = [(-0.70, -0.62, "PTeal"), (0.0, -0.62, "PAmber"),
               (0.70, -0.62, "PViolet")]
    ptops = []
    for dx, dy, colr in pillars:
        h = 0.95
        c = (px + dx, py + dy, pz - 0.03 - h / 2.0)
        sc.box(c, (0.17, 0.17, h), base=colr, opacity=0.82, ambient=0.44,
               diffuse=0.46, edge_style="%s!80!black,line width=0.3pt" % colr)
        sc.polyline([(c[0], c[1], pz - 0.03), (px, py, pz - 0.01)],
                    "%s,line width=0.60pt" % colr, priority=2)
        ptops.append((c[0], c[1], c[2] - h / 2.0))

    # the edge the secant route does not have
    pa, pb = top("secant"), pos("nontriv")
    stop = tuple(pa[k] + 0.55 * (pb[k] - pa[k]) for k in range(3))
    sc.polyline([pa, stop],
                "PClay!55,line width=1.0pt,dash pattern=on 1.6pt off 2.4pt",
                priority=4)
    for sx, sy in ((-1, -1), (-1, 1)):
        sc.polyline([(stop[0] + 0.19 * sx, stop[1] + 0.19 * sy, stop[2]),
                     (stop[0] - 0.19 * sx, stop[1] - 0.19 * sy, stop[2])],
                    "PClay,line width=1.5pt", priority=5)

    # the bounded criterion, closed on itself: a loop in a vertical plane
    qx, qy, qz = pos("P1")
    loop = [(qx + 0.30 * math.cos(t), qy, qz + 0.42 + 0.30 * math.sin(t))
            for t in [-math.pi / 2 + 0.35 + 2 * math.pi * k / 48
                      for k in range(44)]]
    sc.arrow(loop, "PSlate,line width=0.85pt", priority=4)

    P.add(pos("HC"), r"the Hodge conjecture", "text=PIndigo", side="L")
    P.add(pos("HC_ab"), r"abelian varieties", "text=PIndigo", side="L")
    P.add(pos("weil_all"), r"Weil classes, every CM field", "text=PIndigo",
          side="L")
    P.add(pos("weil_iq"), r"$\mathbf{W}(K,n,\delta)$, $K$ quadratic",
          "text=PIndigo", side="L")
    P.add(pos("triv"), r"$\delta=\delta_{0}$", "text=PIndigo", side="L")
    P.add(pos("base"), r"a base point in every family", "text=PGrass",
          side="L")
    P.add(pos("P2"), r"(P2) the semiregularity criterion", "text=PGrass",
          side="L")
    P.add(ptops[0], r"$\dim\mathrm{Ext}^{2}=2n(2n-1)$ suffices", "text=PTeal",
          side="L")
    P.add(ptops[1], r"support of codimension $<n$", "text=PAmber", side="L")
    P.add(ptops[2], r"action through $\wedge^{*}P\oplus\wedge^{*}Q$",
          "text=PViolet", side="L")
    P.add(pos("F3"), r"(F3) varieties not of abelian type", "text=PClay",
          side="R")
    P.add(pos("F2"), r"(F2) classes beyond the Weil lines", "text=PClay",
          side="R")
    P.add(pos("weil_cm"), r"fields of degree $\ge4$", "text=PIndigo",
          side="R")
    P.add(pos("nontriv"), r"$\delta\ne\delta_{0}$", "text=PIndigo", side="R")
    P.add(stop, r"never reached", "text=PClay", side="R")
    P.add(pos("secant"), r"the secant route", "text=PClay", side="R")
    P.add((qx + 0.30, qy, qz + 0.42), r"(P1): equivalent to its conclusion",
          "text=PSlate", side="R")

    write("fig_closure",
          "The implication graph of the scope section: the spine of derived "
          "statements, the open statements at the level where each is "
          "needed, and the propagation statement with its three constraints.",
          sc, P)


if __name__ == "__main__":
    fig_closure()
