#!/usr/bin/env python3
"""
make_frontier.py

Five diagrams for the subsections on the Lefschetz standard conjecture and on
the Mumford target.

  fig_frontier       the rule set of the closure theorem with the rules of the
                     literature added, drawn as a hypergraph: a rule with
                     several premises is a junction marked with a wedge, and
                     each arrow carries the result that proves it.  The four
                     minimal sufficient sets are drawn as nested ribbons under
                     the arrows they use and listed as route cards below.
                     Clay marks an open statement, grass what the paper
                     proves, indigo a derived statement; a small indigo tag
                     marks every open statement that the conjecture implies.

  fig_lefschetzgrid  the summands H^p(C,R^q) of the cohomology of an abelian
                     scheme over a curve, for relative dimension four, with
                     the eigenvalue 2^q of [2]^* on each row, the dashed
                     diagonals that group the summands of one H^k(W), the
                     hard Lefschetz axis, the four operators of the proof, the
                     weight of the sl_2 action on each column, and the values
                     of the outer columns for a Mumford family.

  fig_propagation    propagation along a compact Shimura curve: an algebraic
                     class at a CM point is carried by the Gysin map and the
                     base operator to a global class, algebraic when the total
                     space satisfies the Lefschetz standard conjecture, whose
                     restriction to every fibre is the invariant part; the CM
                     points and the isogenies between their fibres give a
                     dense countable set only, which is why the spreading
                     lemma needs uncountably many points.

  fig_rigidity       the rigidity of the exceptional classes: the nested Hodge
                     loci through the square of a Mumford fourfold in the
                     Siegel space of dimension 36, with tangent dimensions 20,
                     10 and 1, the compact Mumford curve with its CM points
                     away from the boundary, and the nine weight blocks of
                     sp^{-1,1} with their dimensions and the forms whose
                     product is the Gram determinant of each block.

  fig_bypass         the audit of the bypass mechanisms for the Mumford
                     target: each spoke is one mechanism, with its status
                     and the result that settles it.

Every label is written as  \\node[...] at (x,y) {...};  so that checkfigs.py
can read it back and test it for overlaps.
"""
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))

HEAD = r"""%% {name}.tex   (generated by make_frontier.py; do not edit by hand)
%% {blurb}
\documentclass[tikz,border=8pt]{{standalone}}
\usepackage{{amsmath,amssymb}}
\usetikzlibrary{{arrows.meta,calc,decorations.pathreplacing}}
\input{{palette}}
\newcommand{{\hcimp}}{{\,\textcolor{{PIndigo}}{{\tiny$\Leftarrow\mathbf{{HC}}$}}}}
\begin{{document}}
\begin{{tikzpicture}}[x=1cm,y=1cm,line join=round,line cap=round,
  font=\small,text=PInk]
"""
TAIL = r"""\end{tikzpicture}
\end{document}
"""

TIP = r"-{Stealth[length=5pt,width=4pt]}"


def box(x, y, text, fill, draw, w=None, lw=0.6, h=None, font=None,
        sharp=False):
    opts = []
    if w is not None:
        opts.append("minimum width=%.2fcm" % w)
    if h is not None:
        opts.append("minimum height=%.2fcm" % h)
    if font is not None:
        opts.append("font=%s" % font)
    extra = ("," + ",".join(opts)) if opts else ""
    rc = "" if sharp else "rounded corners=2.5pt,"
    return (r"  \node[draw=%s,fill=%s,%sinner sep=3pt,"
            r"line width=%.2fpt,align=center%s] at (%.2f,%.2f) {%s};"
            % (draw, fill, rc, lw, extra, x, y, text) + "\n")


def arrow(a, b, color, bend=None, style="", lw=0.8):
    bend_s = "" if bend is None else ",bend %s" % bend
    return (r"  \draw[%s,line width=%.2fpt,%s%s%s] (%.2f,%.2f) to (%.2f,%.2f);"
            % (color, lw, TIP, bend_s, style, a[0], a[1], b[0], b[1]) + "\n")


def curve(a, c1, c2, b, color, lw=0.8, tip=True, style=""):
    t = ("," + TIP) if tip else ""
    return (r"  \draw[%s,line width=%.2fpt%s%s] (%.2f,%.2f) .. controls "
            r"(%.2f,%.2f) and (%.2f,%.2f) .. (%.2f,%.2f);"
            % (color, lw, t, style, a[0], a[1], c1[0], c1[1], c2[0], c2[1],
               b[0], b[1]) + "\n")


def line(points, color, lw=0.6, style=""):
    pts = " -- ".join("(%.2f,%.2f)" % p for p in points)
    return r"  \draw[%s,line width=%.2fpt%s] %s;" % (color, lw, style, pts) + "\n"


def ribbon(points, color, width):
    """A thick smooth band under the arrows of one route."""
    pts = " ".join("(%.2f,%.2f)" % p for p in points)
    return (r"  \draw[%s,line width=%.1fpt,line cap=round,line join=round]"
            r" plot[smooth,tension=0.55] coordinates {%s};"
            % (color, width, pts) + "\n")


def label(x, y, text, color="PSlate", anchor=None, size=r"\scriptsize",
          extra=""):
    an = "" if anchor is None else ",anchor=%s" % anchor
    return (r"  \node[text=%s,inner sep=1pt,align=center,font=%s%s%s]"
            r" at (%.2f,%.2f) {%s};" % (color, size, an, extra, x, y, text)
            + "\n")


def junction(x, y, color):
    """A rule with several premises: a small disc with a wedge.  The text is
    pure mathematics with no printable letters, so checkfigs treats it as a
    dot, and it is placed by hand away from every label."""
    return (r"  \node[circle,draw=%s,fill=white,line width=0.7pt,inner sep=0.6pt,"
            r"font=\scriptsize] at (%.2f,%.2f) {$\wedge$};" % (color, x, y)
            + "\n")


def dot(x, y, color, r=1.8, hollow=False):
    if hollow:
        return (r"  \draw[%s,fill=white,line width=0.6pt] (%.2f,%.2f) circle "
                r"(%.1fpt);" % (color, x, y, r) + "\n")
    return r"  \fill[%s] (%.2f,%.2f) circle (%.1fpt);" % (color, x, y, r) + "\n"


# ---------------------------------------------------------------- frontier
def seg(spec):
    """The TikZ path of one edge: a straight segment or a cubic."""
    if len(spec) == 2:
        a, b = spec
        return "(%.2f,%.2f) -- (%.2f,%.2f)" % (a[0], a[1], b[0], b[1])
    a, c1, c2, b = spec
    return ("(%.2f,%.2f) .. controls (%.2f,%.2f) and (%.2f,%.2f) .. (%.2f,%.2f)"
            % (a[0], a[1], c1[0], c1[1], c2[0], c2[1], b[0], b[1]))


def frontier():
    out = []
    OPEN, OPENF = "PClay", "WClay"
    DER, DERF = "PIndigo", "WBlue"
    PRO, PROF = "PGrass", "WTeal"
    # route colours: the four minimal sufficient sets
    RC = {1: "PMag!22", 2: "PAmber!36", 3: "PTeal!30", 4: "PViolet!24"}
    RD = {1: "PMag", 2: "PAmber", 3: "PTeal", 4: "PViolet"}
    RW = {4: 15.0, 3: 11.0, 2: 6.5, 1: 8.0}

    HC = (0.00, 7.70)
    AV = (-3.40, 5.70)
    F3 = (1.80, 5.70)
    M = (5.40, 5.70)
    WE = (-5.70, 3.70)
    F2 = (-2.30, 3.70)
    V = (1.80, 3.70)
    L = (5.40, 1.50)
    P2 = (-6.70, 1.50)
    BA = (-3.60, 1.50)
    J1 = (-0.85, 6.70)       # AV and F3 give HC
    J2 = (3.70, 7.70)        # L and M give HC
    J3 = (-4.05, 4.75)       # Weil classes and F2 give AV
    J6 = (-5.25, 2.60)       # base points and P2 give the Weil classes

    # every edge once, as a path; the ribbons and the arrows share it
    E = {
        "AV-J1": ((AV[0] + 0.55, AV[1] + 0.40), (J1[0] - 0.16, J1[1] - 0.09)),
        "F3-J1": ((F3[0] - 0.55, F3[1] + 0.40), (J1[0] + 0.16, J1[1] - 0.08)),
        "J1-HC": ((J1[0] + 0.10, J1[1] + 0.16), (HC[0] - 0.50, HC[1] - 0.42)),
        "M-J2": ((M[0] - 0.35, M[1] + 0.40), (M[0] - 0.60, 7.10),
                 (J2[0] + 0.45, 7.45), (J2[0] + 0.14, J2[1] - 0.10)),
        "L-J2": ((L[0] + 1.10, L[1] + 0.05), (8.20, 2.40), (8.10, 7.70),
                 (J2[0] + 0.19, J2[1] + 0.02)),
        "J2-HC": ((J2[0] - 0.19, J2[1]), (HC[0] + 1.85, HC[1])),
        "WE-J3": ((WE[0] + 0.40, WE[1] + 0.42), (J3[0] - 0.14, J3[1] - 0.12)),
        "F2-J3": ((F2[0] - 0.45, F2[1] + 0.40), (J3[0] + 0.15, J3[1] - 0.10)),
        "J3-AV": ((J3[0] + 0.10, J3[1] + 0.16), (AV[0] - 0.35, AV[1] - 0.40)),
        "V-AV": ((V[0] - 0.70, V[1] + 0.40), (0.70, 4.80), (-1.30, 5.00),
                 (AV[0] + 1.35, AV[1] - 0.25)),
        "L-V": ((L[0] - 1.10, L[1] + 0.25), (V[0] + 0.55, V[1] - 0.42)),
        "P2-J6": ((P2[0] + 0.35, P2[1] + 0.42), (J6[0] - 0.15, J6[1] - 0.11)),
        "BA-J6": ((BA[0] - 0.65, BA[1] + 0.45), (J6[0] + 0.15, J6[1] - 0.10)),
        "J6-WE": ((J6[0] - 0.06, J6[1] + 0.17), (WE[0] + 0.25, WE[1] - 0.42)),
    }
    ROUTES = {
        4: ["P2-J6", "BA-J6", "J6-WE", "WE-J3", "F2-J3", "J3-AV", "AV-J1",
            "F3-J1", "J1-HC"],
        3: ["V-AV", "AV-J1", "F3-J1", "J1-HC"],
        2: ["L-V", "V-AV", "AV-J1", "F3-J1", "J1-HC"],
        1: ["L-J2", "M-J2", "J2-HC"],
    }
    # ribbons, widest first, so that a shared edge shows nested bands
    for r in (4, 3, 2, 1):
        for e in ROUTES[r]:
            out.append(r"  \draw[%s,line width=%.1fpt,line cap=round] %s;"
                       % (RC[r], RW[r], seg(E[e])) + "\n")

    # nodes; the tag \hcimp marks an open statement that HC implies
    out.append(box(HC[0], HC[1], r"$\mathbf{HC}$\\{\scriptsize "
                   r"$\Hdg^{p}(X)=\mathrm{Alg}^{p}(X)$ for all $X$}",
                   DERF, DER, lw=0.9))
    out.append(box(AV[0], AV[1], r"conjecture for\\abelian varieties",
                   DERF, DER))
    out.append(box(F3[0], F3[1], r"(F3)\hcimp\\{\scriptsize $X$ not abelian}",
                   OPENF, OPEN))
    out.append(box(M[0], M[1], r"(M)\hcimp\\{\scriptsize Hodge $=$ motivated}",
                   OPENF, OPEN))
    out.append(box(WE[0], WE[1], r"Weil classes\\{\scriptsize "
                   r"$\textstyle\bigwedge^{2n}_{K}H^{1}$, every CM $K$}",
                   DERF, DER))
    out.append(box(F2[0], F2[1], r"(F2)\hcimp\\{\scriptsize beyond Weil lines}",
                   OPENF, OPEN))
    out.append(box(V[0], V[1], r"(V)\hcimp\\{\scriptsize alg.\ at $s\Rightarrow$ "
                   r"alg.\ at $t$}", OPENF, OPEN))
    out.append(box(L[0], L[1], r"(L)\hcimp\\{\scriptsize $B(X)$: "
                   r"$\Lambda$ algebraic}", OPENF, OPEN))
    out.append(box(P2[0], P2[1], r"(P2)\\{\scriptsize semiregular $E$}",
                   OPENF, OPEN))
    out.append(box(BA[0], BA[1], r"base points,\\reduction, orbits",
                   PROF, PRO))

    # arrows
    col = {"AV-J1": DER, "F3-J1": OPEN, "J1-HC": DER, "M-J2": OPEN,
           "L-J2": OPEN, "J2-HC": DER, "WE-J3": DER, "F2-J3": OPEN,
           "J3-AV": DER, "V-AV": OPEN, "L-V": OPEN, "P2-J6": OPEN,
           "BA-J6": PRO, "J6-WE": DER}
    for e, spec in E.items():
        lw = 1.0 if e in ("J1-HC", "J2-HC", "J3-AV", "J6-WE") else 0.8
        out.append(r"  \draw[%s,line width=%.2fpt,%s] %s;"
                   % (col[e], lw, TIP, seg(spec)) + "\n")
    for j in (J1, J2, J3, J6):
        out.append(junction(j[0], j[1], DER))

    # rule labels, each naming the result that proves the rule
    out.append(label(J1[0] - 0.42, J1[1] + 0.20, r"\S16.5", DER,
                     anchor="east"))
    out.append(label(J3[0] - 0.42, J3[1] + 0.12, r"\S16.5", DER,
                     anchor="east"))
    out.append(label(J2[0], J2[1] + 0.62, r"Prop.~16.16\\Andr\'e", DER))
    out.append(label(-0.55, 5.45, r"Thm.~16.18\\Deligne, Andr\'e", DER))
    out.append(label(4.35, 2.85, r"Prop.~16.17\\Andr\'e", DER))
    out.append(label(-6.75, 2.85, r"Thm.~14.81\\Thm.~15.6", PRO))

    # route cards
    cards = [(-5.60, 1, r"$\{$L, M$\}$", r"(L)$\wedge$(M)$\Rightarrow\mathbf{HC}$"),
             (-1.90, 2, r"$\{$L, F3$\}$",
              r"(L)$\Rightarrow$(V)$\Rightarrow$ab.$\wedge$(F3)"),
             (1.80, 3, r"$\{$V, F3$\}$", r"(V)$\Rightarrow$ab.$\wedge$(F3)"),
             (5.50, 4, r"$\{$P2, F2, F3$\}$", r"the route of this paper")]
    for x, r, head, sub in cards:
        out.append(box(x, -0.35, r"\textbf{%d}\enspace%s\\{\scriptsize %s}"
                       % (r, head, sub), RC[r], RD[r], w=3.30, lw=0.8))
    out.append(label(0.00, -1.25, r"the four minimal sufficient sets of the "
                     r"closure theorem, drawn as nested ribbons above",
                     "PInk"))

    # legend
    out.append(box(-6.20, -2.05, r"open", OPENF, OPEN, w=1.3))
    out.append(box(-4.45, -2.05, r"proved here", PROF, PRO, w=2.0))
    out.append(box(-2.55, -2.05, r"derived", DERF, DER, w=1.4))
    out.append(label(-1.35, -2.05, r"\hcimp\ implied by $\mathbf{HC}$", "PInk",
                     anchor="west"))
    out.append(junction(2.35, -2.05, DER))
    out.append(label(2.65, -2.05, r"rule with several premises", "PInk",
                     anchor="west"))
    return "".join(out)


# ---------------------------------------------------------------- the grid
def grid():
    out = []
    g = 4
    xs = {0: 0.0, 1: 3.9, 2: 7.8}
    dy = 0.66
    W = 1.62
    # the hard Lefschetz axis q = g, behind everything
    out.append(line([(-2.45, g * dy), (xs[2] + 0.82, g * dy)], "PMag!55",
                    lw=0.5, style=",dash pattern=on 3pt off 2pt"))
    # the diagonals of constant total degree k = p + q, behind the boxes
    for k in range(0, 2 * g + 3):
        pts = [(xs[p], (k - p) * dy) for p in (0, 1, 2) if 0 <= k - p <= 2 * g]
        if len(pts) >= 2:
            out.append(line(pts, "PRule", lw=0.5,
                            style=",dash pattern=on 1.5pt off 1.5pt"))
    for p in (0, 1, 2):
        for q in range(2 * g + 1):
            y = q * dy
            inv = (p in (0, 2)) and q % 2 == 0
            fill = "WOchre" if inv else ("WSlate" if p == 1 else "WBlue")
            draw = "POchre" if inv else "PSlate"
            out.append(r"  \node[draw=%s,fill=%s,rounded corners=1.5pt,"
                       r"minimum width=%.2fcm,minimum height=0.46cm,inner sep=1pt,"
                       r"line width=0.5pt] at (%.2f,%.2f) {\scriptsize "
                       r"$H^{%d}(C,R^{%d})$};" % (draw, fill, W, xs[p], y, p, q)
                       + "\n")
    # eigenvalues of [2]^* on each row
    out.append(label(-2.95, 2 * g * dy + 0.72, r"$[2]^{*}$", "PInk",
                     size=r"\small"))
    for q in range(2 * g + 1):
        out.append(label(-2.95, q * dy, r"$2^{%d}$" % q, "PSlate"))
    out.append(label(-2.95, -0.62, r"weight", "PSlate"))
    # the weights of H = H_rel + H_C on each column: (q-4)+(p-1)
    for p in (0, 1, 2):
        out.append(label(xs[p], -0.62, r"$H=q-%d%s$" %
                         (g + (1 - p), "" if p != 1 else ""), "PInk"))
    out.append(label(xs[0], -1.22, r"$p=0$: invariants $I_{q}$", "PInk"))
    out.append(label(xs[1], -1.22, r"$p=1$: killed by $L_{C}$ and "
                     r"$\Lambda_{C}$", "PInk"))
    out.append(label(xs[2], -1.22, r"$p=2$: coinvariants $I_{q}\cup f$",
                     "PInk"))
    # relative operators on the left column, rows 2 and 4
    out.append(arrow((xs[0] - 0.95, 2 * dy), (xs[0] - 0.95, 4 * dy), "PTeal",
                     bend="left=35", lw=0.9))
    out.append(arrow((xs[0] + 0.95, 4 * dy - 0.05), (xs[0] + 0.95, 2 * dy + 0.05),
                     "PTeal", bend="left=35", lw=0.9))
    out.append(label(xs[0] - 1.48, 3 * dy, r"$L_{\mathrm{rel}}$", "PTeal",
                     anchor="east"))
    out.append(label(xs[0] + 1.45, 3 * dy + 0.02, r"$\Lambda_{\mathrm{rel}}$",
                     "PTeal", anchor="west"))
    # base operators between the outer boxes of the top row
    ytop = 2 * g * dy + 0.26
    out.append(arrow((xs[0] + 0.35, ytop), (xs[2] - 0.35, ytop), "POchre",
                     bend="left=18", lw=0.9))
    out.append(arrow((xs[2] + 0.35, ytop), (xs[0] - 0.35, ytop), "POchre",
                     bend="right=36", lw=0.9))
    out.append(label(xs[1], ytop + 0.88, r"$L_{C}=\cup\,mf$", "POchre"))
    out.append(label(xs[1], ytop + 1.98, r"$\Lambda_{C}=\sum(M^{-1})_{kj}"
                     r"\,b_{k}\times a_{j}$", "POchre"))
    # the formula panel
    out.append(box(xs[1], ytop + 3.00,
                   r"$\Lambda=\Lambda_{\mathrm{rel}}+\Lambda_{C}$,\quad "
                   r"$\Lambda_{\mathrm{rel}}(x)=D^{-1}\,x\star\gamma$,\quad "
                   r"$\gamma=\ell^{g-1}/(g-1)!$\\[1pt]"
                   r"$[L_{W},\Lambda]=H_{\mathrm{rel}}+H_{C}$ acts on "
                   r"$H^{p}(C,R^{q})$ by $(q-g)+(p-1)=\deg-\dim W$",
                   "WSlate", "PSlate", lw=0.6))
    # Mumford values of the outer columns
    out.append(label(9.20, 2 * g * dy + 0.72, r"Mumford", "PMag",
                     size=r"\small"))
    for q in range(2 * g + 1):
        txt = (r"$\QQ\,\ell^{%d}f$" % (q // 2)) if q % 2 == 0 else r"$0$"
        if q == 0:
            txt = r"$\QQ\,f$"
        if q == 2:
            txt = r"$\QQ\,\ell f$"
        out.append(label(xs[2] + 0.98, q * dy, txt, "PMag", anchor="west"))
    out.append(label(1.95, g * dy + 0.22, r"$q=g$", "PMag", size=r"\tiny"))
    return "".join(out)


# ---------------------------------------------------------------- propagation
def propagation():
    out = []

    def cy(x):
        return 0.28 * math.sin(0.55 * x) + 0.10 * math.sin(1.7 * x)

    xs = [i * 0.1 for i in range(-4, 115)]
    pts = " -- ".join("(%.2f,%.3f)" % (x, cy(x)) for x in xs)
    out.append(r"  \draw[PInk,line width=1.1pt] %s;" % pts + "\n")
    out.append(label(11.95, cy(11.4) + 0.05, r"$C=\Gamma\backslash\mathfrak{H}$",
                     "PInk", size=r"\small", anchor="west"))
    out.append(label(11.95, cy(11.4) - 0.45, r"compact", "PSlate",
                     anchor="west"))
    # CM points: a countable dense set, drawn as small hollow dots
    cms = [0.35, 1.20, 2.05, 2.75, 3.55, 4.30, 6.05, 6.80, 7.50, 8.20, 9.95,
           10.70, 11.25]
    for x in cms:
        out.append(dot(x, cy(x), "PGrass", r=1.5, hollow=True))
    # isogeny arcs between CM fibres (Hecke orbit of the base point)
    for a, b in ((1.20, 2.75), (2.75, 4.30), (1.20, 6.80), (6.80, 8.20)):
        mid = 0.5 * (a + b)
        dip = 0.16 + 0.035 * (b - a)
        out.append(r"  \draw[PGrass!70,line width=0.5pt,dash pattern=on 2pt "
                   r"off 1.5pt,-{Stealth[length=3pt,width=2.5pt]}] (%.2f,%.3f)"
                   r" .. controls (%.2f,%.3f) and (%.2f,%.3f) .. (%.2f,%.3f);"
                   % (a, cy(a) - 0.08, a + 0.3, cy(a) - dip - 0.12,
                      b - 0.3, cy(b) - dip - 0.12, b, cy(b) - 0.08)
                   + "\n")
    out.append(label(4.70, -1.80, r"isogenies $X_{c}\to X_{c'}$ along Hecke "
                     r"orbits carry $y$: a dense but countable set",
                     "PGrass"))
    # three fibres: a CM point, a general point, a very general point
    fib = [(1.20, "PGrass", "WTeal", r"$y$", r"$X_{c}\times X_{c}$"),
           (5.20, "PSlate", "WSlate", r"$H^{*}(W_{s})$", r"$W_{s}$"),
           (9.20, "PClay", "WClay", r"$\xi_{t}$", r"$W_{t}$")]
    for x, dr, fl, inner, name in fib:
        y0 = cy(x)
        out.append(r"  \draw[%s,fill=%s,line width=0.7pt,rounded corners=7pt]"
                   r" (%.2f,%.2f) rectangle (%.2f,%.2f);"
                   % (dr, fl, x - 0.62, y0 + 0.40, x + 0.62, y0 + 2.30) + "\n")
        # a torus-like decoration inside the fibre
        out.append(r"  \draw[%s!60,line width=0.5pt] (%.2f,%.2f) ellipse "
                   r"(0.42 and 0.20);" % (dr, x, y0 + 1.85) + "\n")
        out.append(r"  \draw[%s!60,line width=0.5pt] (%.2f,%.2f) arc (200:340:"
                   r"0.20 and 0.07);" % (dr, x - 0.19, y0 + 1.87) + "\n")
        out.append(r"  \draw[%s!60,line width=0.5pt] (%.2f,%.2f) arc (160:20:"
                   r"0.14 and 0.05);" % (dr, x - 0.13, y0 + 1.83) + "\n")
        out.append(r"  \draw[%s,line width=0.7pt] (%.2f,%.3f) -- (%.2f,%.2f);"
                   % (dr, x, y0, x, y0 + 0.40) + "\n")
        out.append(dot(x, y0, dr, r=2.0))
        out.append(label(x, y0 + 1.05, inner, dr, size=r"\small"))
    out.append(label(1.20, -1.05, r"CM point $c$: $y$ algebraic\\"
                     r"(Thm.~16.26, via Markman)", "PGrass"))
    out.append(label(5.20, -0.95, r"general point", "PSlate"))
    out.append(label(9.20, -1.05, r"very general $t$:\\"
                     r"$\xi_{t}=$ invariant part of $y$", "PClay"))
    # the global class
    out.append(box(5.20, 4.75, r"$u=m\,\Lambda_{C}(i_{c*}y)\in "
                   r"H^{q}_{(q)}(W)$\\[1pt]{\scriptsize algebraic when $B(W)$ "
                   r"holds; $f\cup u=i_{c*}y$}", "WOchre", "POchre", lw=0.8))
    out.append(arrow((1.75, 2.80), (3.25, 4.40), "PGrass", bend="left=14",
                     lw=0.9))
    out.append(arrow((7.15, 4.40), (8.65, 2.80), "PClay", bend="left=14",
                     lw=0.9))
    out.append(label(1.55, 3.95, r"$i_{c*}$: Gysin,\\then $\Lambda_{C}$",
                     "PGrass"))
    out.append(label(8.95, 3.95, r"restrict:\\$u|_{W_{t}}=\xi_{t}$", "PClay"))
    # the pairing that pins down the restriction
    out.append(label(5.20, 3.30, r"$\int_{W_{c}}u\cup w=\int_{W_{c}}"
                     r"y\cup w$, $w$ invariant", "POchre"))
    # the spreading dichotomy
    out.append(box(5.20, -2.85, r"Lemma~16.24: $\xi_{t}$ algebraic for "
                   r"uncountably many $t$ $\Longrightarrow$ $d\,\xi_{t}$ "
                   r"algebraic for every $t$\\[1pt]{\scriptsize so the CM points"
                   r" alone never suffice; $B(W)$ supplies the global class "
                   r"$u$ instead (Thm.~16.25)}", "WSlate", "PSlate", lw=0.6))
    return "".join(out)


# ---------------------------------------------------------------- rigidity
def ellipse(cx, cy, rx, ry, draw, fill, lw=0.7, style=""):
    return (r"  \draw[%s,fill=%s,line width=%.2fpt%s] (%.2f,%.2f) ellipse "
            r"(%.2f and %.2f);" % (draw, fill, lw, style, cx, cy, rx, ry) + "\n")


def rigidity():
    out = []
    # left panel: the Siegel space and the nested Hodge loci
    out.append(r"  \draw[PSlate,fill=WSlate,line width=0.8pt,rounded corners=26pt]"
               r" (-0.20,-0.30) rectangle (7.40,6.10);" + "\n")
    # the boundary, drawn as a dashed rim with cusps
    out.append(r"  \draw[PSlate!70,line width=0.6pt,dash pattern=on 3pt off 2pt,"
               r"rounded corners=30pt] (-0.45,-0.55) rectangle (7.65,6.35);"
               + "\n")
    for x, y in ((-0.45, 2.90), (7.65, 2.90), (3.60, -0.55)):
        out.append(r"  \fill[PSlate] (%.2f,%.2f) circle (1.6pt);" % (x, y) + "\n")
    out.append(label(3.60, 6.72, r"$\mathfrak{S}_{8}$, $\dim 36$: principally "
                     r"polarised $8$-folds near $X_{c}\times X_{c}$", "PInk",
                     size=r"\small"))
    out.append(label(3.60, -0.95, r"boundary with cusps: degenerations of "
                     r"$\mathfrak{S}_{8}$", "PSlate"))
    out.append(ellipse(3.70, 2.75, 3.05, 2.35, "PIndigo", "WBlue", lw=0.8))
    out.append(ellipse(3.95, 2.45, 2.10, 1.55, "PTeal", "WTeal", lw=0.8))
    out.append(label(3.70, 4.55, r"$T=20$: $a_{0}=a_{1}=a_{2}=a_{3}$",
                     "PIndigo"))
    out.append(label(3.95, 3.35, r"$T=10$: $a_{1}=a_{2}=a_{3}$\\"
                     r"diagonal $\mathfrak{S}_{4}$", "PTeal"))
    # the compact Mumford curve: a closed loop with CM points
    loop = []
    for i in range(0, 73):
        th = 2 * math.pi * i / 72
        r = 0.95 + 0.12 * math.cos(3 * th)
        loop.append((4.10 + 1.25 * r * math.cos(th),
                     2.05 + 0.55 * r * math.sin(th)))
    out.append(r"  \draw[PClay,line width=1.3pt] %s -- cycle;"
               % " -- ".join("(%.3f,%.3f)" % p for p in loop[:-1]) + "\n")
    for i in range(0, 72, 7):
        out.append(dot(loop[i][0], loop[i][1], "PGrass", r=1.4, hollow=True))
    out.append(dot(loop[12][0], loop[12][1], "PClay", r=2.2))
    out.append(label(4.10, 2.05, r"$C$: $T=1$", "PClay"))
    out.append(label(1.45, 0.25, r"$T$ = tangent dimension\\of the Hodge locus",
                     "PSlate"))
    out.append(label(6.25, 0.30, r"no cusp: $D$\\is a division\\algebra",
                     "PSlate"))
    # right panel: the nine weight blocks
    bx, by, s = 9.80, 0.55, 1.62
    blocks = {(-2, -2): (3, r"$P_{1}P_{2}Q_{1}$"),
              (-2, 0): (4, r"$P_{1}P_{2}Q_{1}Q_{2}$"),
              (-2, 2): (3, r"$P_{1}P_{2}Q_{1}$"),
              (0, -2): (4, r"$P_{1}P_{2}Q_{1}Q_{3}$"),
              (0, 0): (8, r"$R\,P_{1}P_{2}$\\$Q_{1}Q_{2}Q_{3}Q_{4}$"),
              (0, 2): (4, r"$P_{1}P_{2}Q_{1}Q_{3}$"),
              (2, -2): (3, r"$P_{1}P_{2}Q_{1}$"),
              (2, 0): (4, r"$P_{1}P_{2}Q_{1}Q_{2}$"),
              (2, 2): (3, r"$P_{1}P_{2}Q_{1}$")}
    for (m1, m2), (d, forms) in blocks.items():
        i, j = (m1 + 2) // 2, (m2 + 2) // 2
        x = bx + i * s
        y = by + (2 - j) * s * 0.92
        fill = "WClay" if (m1, m2) == (0, 0) else "WOchre"
        draw = "PClay" if (m1, m2) == (0, 0) else "POchre"
        head = (r"$8=7+1$" if (m1, m2) == (0, 0) else r"$%d$" % d)
        out.append(r"  \node[draw=%s,fill=%s,rounded corners=2pt,line width=0.6pt,"
                   r"minimum width=%.2fcm,minimum height=%.2fcm,inner sep=1pt,"
                   r"align=center,font=\scriptsize] at (%.2f,%.2f) {%s\\%s};"
                   % (draw, fill, s - 0.08, s * 0.92 - 0.08, x, y, head, forms)
                   + "\n")
    for k, m in enumerate((-2, 0, 2)):
        out.append(label(bx + k * s, by + 2 * s * 0.92 + 0.98, r"$%+d$" % m
                         if m else r"$0$", "PInk"))
        out.append(label(bx - 1.10, by + (2 - k) * s * 0.92, r"$%+d$" % m
                         if m else r"$0$", "PInk"))
    out.append(label(bx + s, by + 2 * s * 0.92 + 1.45,
                     r"weight $\mu_{1}$ of $\mathfrak{sl}_{2}(V_{1})$", "PInk"))
    out.append(label(bx - 1.55, by + s * 0.92,
                     r"weight $\mu_{2}$ of $\mathfrak{sl}_{2}(V_{2})$", "PInk",
                     extra=",rotate=90"))
    out.append(label(bx + s, by - 1.00,
                     r"$\mathfrak{sp}^{-1,1}$: $3+4+3+4+8+4+3+4+3=36$",
                     "PInk"))
    out.append(label(bx + s, by - 1.50,
                     r"in $(0,0)$ one kernel vector, the curve direction "
                     r"$\kappa$", "PClay"))
    out.append(label(bx + s, by - 2.00,
                     r"$HT^{2}=28+64+28$: $46$ blocks, kernel $\CC\kappa$ "
                     r"if $a_{0}+\mathrm{tr}\,\alpha\ne0$", "PIndigo"))
    # the forms and their sums of squares
    out.append(box(5.70, -2.55,
                   r"$2P_{1}=\sum_{i<j}(a_{i}-a_{j})^{2}$,\quad "
                   r"$2P_{2}=\sum_{i<j}(a_{i}+a_{j})^{2}$,\quad "
                   r"$R=a_{2}^{2}+a_{3}^{2}$,\quad "
                   r"$Q_{4}=(3a_{1}-a_{0}-a_{2}-a_{3})^{2}+16(a_{2}-a_{3})^{2}$"
                   r"\\[1pt]"
                   r"$33Q_{1}=3(11a_{1}-a_{0}-5a_{2}-5a_{3})^{2}"
                   r"+8(6a_{2}-a_{0}-5a_{3})^{2}+88(a_{3}-a_{0})^{2}$,\quad "
                   r"$S_{1}=(a_{0}-a_{2})^{2}+3(a_{1}-a_{3})^{2}$",
                   "WSlate", "PSlate"))
    out.append(label(5.70, -3.50, r"a rational exceptional class has "
                     r"$(a_{1},a_{2},a_{3})=(\sigma_{1}\alpha,\sigma_{2}\alpha,"
                     r"\sigma_{3}\alpha)$ with $\alpha\in F\setminus\QQ$: "
                     r"pairwise distinct, so every block has full rank",
                     "PInk"))
    return "".join(out)


# ---------------------------------------------------------------- bypass audit
def bypass():
    out = []
    out.append(box(0.0, 0.0, r"\textbf{target}\\$\omega$ algebraic on "
                   r"$X_{t}\times X_{t}$\\{\scriptsize $t\in C$ very general}",
                   "WOchre", "POchre", lw=1.0))
    BLK, BLKF = "PClay", "WClay"
    OPN, OPNF = "PIndigo", "WBlue"
    PAR, PARF = "PGrass", "WTeal"
    # nine spokes, clockwise from the top: (angle, radii of the box centre,
    # text, colours, status, offset of the status from the box centre)
    spokes = [
        (90, (0.0, 4.05), r"\textbf{degeneration}\\{\scriptsize to a cusp of "
         r"the base}", BLKF, BLK, r"blocked: $C$ is compact", (0.0, 0.80)),
        (54, (4.20, 3.30), r"\textbf{larger Hodge locus}\\{\scriptsize deform "
         r"$X_{c}\times X_{c}$ off the curve}", BLKF, BLK,
         r"blocked: tangent space $\CC\kappa$", (0.0, 0.80)),
        (18, (6.75, 1.35), r"\textbf{Hochschild deformations}\\{\scriptsize "
         r"$B$-fields, bivectors, gerbes}", BLKF, BLK,
         r"blocked: $\mathrm{Ann}_{HT^{2}}=\CC\kappa$", (0.0, 0.80)),
        (-18, (6.75, -1.35), r"\textbf{twistor lines}\\{\scriptsize "
         r"hyperholomorphic transport}", BLKF, BLK,
         r"blocked: the locus is a disk", (0.0, -0.82)),
        (-54, (4.70, -3.25), r"\textbf{built from line bundles}\\{\scriptsize "
         r"cones, $\otimes$, $f^{*}$, $f_{*}$, Fourier--Mukai}", BLKF, BLK,
         r"blocked: $\mathrm{ch}$ stays Lefschetz", (0.0, -0.82)),
        (-90, (0.0, -4.85), r"\textbf{CM points, isogenies}\\{\scriptsize "
         r"algebraic at every CM point}", PARF, PAR,
         r"enough iff the\\degrees are bounded", (0.0, -0.95)),
        (-126, (-4.70, -3.25), r"\textbf{reduction mod $p$}\\{\scriptsize "
         r"cycles at every closed point}", PARF, PAR,
         r"enough iff the degrees are\\bounded on a dense set", (0.0, -0.95)),
        (-162, (-6.75, -1.35), r"\textbf{semiregularity}\\{\scriptsize one $E$ "
         r"at one CM point}", OPNF, OPN, r"open: $\dim\mathrm{Ext}^{2}=119$,"
         r"\\$e_{1}+e_{3}\ge400$", (0.0, -0.95)),
        (162, (-6.75, 1.35), r"\textbf{Kuga--Satake}\\{\scriptsize the class "
         r"of one K3 surface $S_{\lambda}$}", OPNF, OPN,
         r"open: $\rho(S_{\lambda})=13$, cubic RM", (0.0, 0.80)),
        (126, (-4.20, 3.30), r"\textbf{motivated classes}\\{\scriptsize "
         r"Andr\'e, deformation}", OPNF, OPN,
         r"equivalent: $B(W\times_{C}W)$", (0.0, 0.80)),
    ]
    TW, TH = 2.05, 0.66     # half sizes of the target box
    BW, BH = 1.75, 0.43     # half sizes of a spoke box
    for ang, pos, text, fill, draw, status, soff in spokes:
        dx, dy = pos
        # the spoke joins the two box boundaries along the line of centres
        t0 = min(TW / abs(dx) if dx else 9e9, TH / abs(dy) if dy else 9e9)
        t1 = min(BW / abs(dx) if dx else 9e9, BH / abs(dy) if dy else 9e9)
        st = (dx * t0, dy * t0)
        en = (dx * (1 - t1), dy * (1 - t1))
        style = ",dash pattern=on 3pt off 2pt" if draw == BLK else ""
        out.append(r"  \draw[%s,line width=0.9pt%s] (%.2f,%.2f) -- (%.2f,%.2f);"
                   % (draw, style, st[0], st[1], en[0], en[1]) + "\n")
        if draw == BLK:
            mx, my = 0.5 * (st[0] + en[0]), 0.5 * (st[1] + en[1])
            out.append(r"  \draw[%s,line width=1.2pt] (%.2f,%.2f) -- (%.2f,%.2f)"
                       r" (%.2f,%.2f) -- (%.2f,%.2f);"
                       % (draw, mx - 0.12, my - 0.12, mx + 0.12, my + 0.12,
                          mx - 0.12, my + 0.12, mx + 0.12, my - 0.12) + "\n")
        out.append(box(dx, dy, text, fill, draw, lw=0.8))
        out.append(label(dx + soff[0], dy + soff[1], status, draw))
    # legend
    out.append(box(-5.40, -6.75, r"blocked by a theorem", BLKF, BLK))
    out.append(box(-0.30, -6.75, r"partial", PARF, PAR))
    out.append(box(4.40, -6.75, r"open, or equivalent", OPNF, OPN))
    return "".join(out)


# ---------------------------------------------------------------- Ext profile
def extprofile():
    out = []
    r = [1, 16, 119, 328, 560, 328, 119, 16, 1]
    H = 4.4 / 560.0
    bw, dx = 0.62, 0.95
    out.append(r"  \definecolor{BEven}{HTML}{4A56B0}" + "\n")
    out.append(r"  \definecolor{BOdd}{HTML}{D67026}" + "\n")
    # recessive grid and one axis
    for v in (100, 200, 300, 400, 500):
        out.append(line([(-0.55, v * H), (8 * dx + 0.55, v * H)], "PRule!60",
                        lw=0.3))
        out.append(label(-0.70, v * H, r"$%d$" % v, "PSlate", anchor="east",
                         size=r"\tiny"))
    out.append(line([(-0.55, 0.0), (8 * dx + 0.55, 0.0)], "PInk", lw=0.6))
    # the Serre mirror
    out.append(line([(4 * dx, 4.90), (4 * dx, 5.30)], "PMag!70", lw=0.5,
                    style=",dash pattern=on 3pt off 2pt"))
    out.append(line([(4 * dx, -0.08), (4 * dx, -0.14)], "PMag!70", lw=0.5))
    out.append(label(4 * dx, 5.55, r"Serre duality: $\mathrm{Ext}^{k}\cong"
                     r"(\mathrm{Ext}^{8-k})^{\vee}$, and $r_{k}=r_{8-k}$",
                     "PMag"))
    for k, v in enumerate(r):
        x = k * dx
        col = "BEven" if k % 2 == 0 else "BOdd"
        h = max(v * H, 0.03)
        out.append(r"  \fill[%s,rounded corners=0.8pt] (%.3f,0) rectangle "
                   r"(%.3f,%.3f);" % (col, x - bw / 2, x + bw / 2, h) + "\n")
        out.append(label(x, h + 0.20, r"$%d$" % v, "PInk", size=r"\scriptsize"))
        out.append(label(x, -0.30, r"$%d$" % k, "PInk", size=r"\scriptsize"))
    out.append(label(4 * dx, -0.75, r"degree $k$ of $HT^{k}$ and "
                     r"$\mathrm{Ext}^{k}(E,E)$", "PInk"))
    out.append(label(-1.55, 2.2, r"$r_{k}=\dim HT^{k}\lrcorner\,\omega$",
                     "PInk", extra=",rotate=90"))
    out.append(label(2 * dx, 119 * H + 0.72, r"$28+63+28$", "PSlate",
                     size=r"\tiny"))
    # legend
    out.append(r"  \fill[BEven,rounded corners=0.8pt] (0.40,5.03) rectangle "
               r"(0.62,5.21);" + "\n")
    out.append(label(0.75, 5.12, r"even $k$", "PInk", anchor="west"))
    out.append(r"  \fill[BOdd,rounded corners=0.8pt] (0.40,4.53) rectangle "
               r"(0.62,4.71);" + "\n")
    out.append(label(0.75, 4.62, r"odd $k$", "PInk", anchor="west"))
    # right panel: the Euler characteristic balance
    cx, cy = 12.2, 2.3
    out.append(line([(cx - 2.2, cy + 0.6), (cx + 2.2, cy + 0.6)], "PInk",
                    lw=1.0))
    out.append(r"  \fill[PInk] (%.2f,%.2f) -- (%.2f,%.2f) -- (%.2f,%.2f) -- "
               r"cycle;" % (cx - 0.22, cy - 0.05, cx + 0.22, cy - 0.05, cx,
                            cy + 0.58) + "\n")
    for sgn in (-1, 1):
        px = cx + sgn * 2.0
        out.append(line([(px, cy + 0.6), (px - 0.55, cy - 0.35)], "PSlate",
                        lw=0.4))
        out.append(line([(px, cy + 0.6), (px + 0.55, cy - 0.35)], "PSlate",
                        lw=0.4))
    out.append(box(cx - 2.0, cy - 0.75, r"$\sum_{k\ \mathrm{even}}e_{k}$\\"
                   r"{\scriptsize$\ge2\cdot1+2\cdot119+560=800$}", "WBlue",
                   "BEven", lw=0.8))
    out.append(box(cx + 2.0, cy - 0.75, r"$\sum_{k\ \mathrm{odd}}e_{k}$\\"
                   r"{\scriptsize$\ge688$ from $HT$}", "WOchre", "BOdd",
                   lw=0.8))
    out.append(label(cx, cy + 1.25, r"$\chi(E,E)=\int_{Y}\ch(E^{\vee})"
                     r"\ch(E)=0$ balances the pans", "PInk"))
    out.append(label(cx, cy - 2.05, r"so the odd side exceeds the "
                     r"Hochschild bound $688$\\by at least $112$, and "
                     r"$e_{1}+e_{3}\ge400$\\when "
                     r"$\mathrm{Ext}^{<0}(E,E)=0$", "PClay"))
    out.append(label(cx, 4.95, r"$\sum_{k}r_{k}=1488$,\quad"
                     r" $\sum_{k}(-1)^{k}r_{k}=112\neq0$", "PInk"))
    return "".join(out)


def write(name, blurb, body):
    path = os.path.join(HERE, name + ".tex")
    with open(path, "w") as f:
        f.write(HEAD.format(name=name, blurb=blurb))
        f.write(body)
        f.write(TAIL)
    print("wrote", path)


if __name__ == "__main__":
    write("fig_frontier",
          "The rule set with the routes of the literature: four minimal "
          "sufficient sets.", frontier())
    write("fig_propagation",
          "Propagation of algebraicity along a compact Shimura curve under the "
          "Lefschetz standard conjecture for the total space.", propagation())
    write("fig_lefschetzgrid",
          "The summands H^p(C,R^q) of an abelian scheme over a curve and the "
          "four operators of the proof.", grid())
    write("fig_rigidity",
          "Rigidity of the exceptional classes on the square of a Mumford "
          "fourfold: nested Hodge loci and the nine weight blocks.",
          rigidity())
    write("fig_bypass",
          "The audit of the bypass mechanisms for the Mumford target.",
          bypass())
    write("fig_extprofile",
          "Lower bounds for the self-Ext of an object with the Chern character "
          "of an exceptional class, and the Euler characteristic balance.",
          extprofile())
