#!/usr/bin/env python3
"""
make_plates.py

Three plates drawn from the equations rather than schematically.  Every
surface here is a real locus: the quadric is x^2 + y^2 - z^2 = 1 with both of
its rulings drawn line by line, the cone is x^2 + y^2 - z^2 = 0, and the
Lagrangian fan is an honest one-parameter family of planes through the origin
of a symplectic four-space, drawn in the three-dimensional slice that carries
it.  Shading is Lambert against a fixed light and the draw order is by depth,
so occlusion is correct; labels are placed outside the ink by place.py and
joined to their anchors by leaders, so nothing overlaps anything.

  fig_quadric    the even spinor variety in the smallest case, a smooth
                 quadric with its two rulings, and the rational secant line
                 meeting it in the two conjugate pure spinors
  fig_lagsweep   the Lagrangian fan: the quaternionic locus of psi is an open
                 piece of LG(n,2n), and as psi varies the loci sweep the
                 family, the rational psi picking out countably many of them
  fig_fibres     the null cone of the hermitian form, the two conjugate
                 isotropic planes, the fibres joining them, and the mixed
                 block the Weil class annihilates
"""
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from render3d import Camera, Scene, addv, smul, sub, unit, cross
from place import Placer

HEAD = r"""%% {name}.tex   (generated by make_plates.py; do not edit by hand)
%% {blurb}
\documentclass[tikz,border=8pt]{{standalone}}
\usepackage{{amsmath,amssymb}}
\usetikzlibrary{{arrows.meta,calc}}
\input{{palette}}
\begin{{document}}
\begin{{tikzpicture}}[x=1cm,y=1cm,line join=round,line cap=round,
  font=\small,text=PInk]
"""
TAIL = "\\end{tikzpicture}\n\\end{document}\n"


def write(name, blurb, sc, P):
    body = sc.emit()
    bad = P.check(body, sc.cam)
    if bad:
        raise SystemExit("placement failure in %s: %s" % (name, bad))
    labels = P.emit(body, sc.cam)
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, name + ".tex"), "w") as f:
        f.write(HEAD.format(name=name, blurb=blurb))
        f.write(body)
        f.write(labels)
        f.write(TAIL)
    print("%-13s %2d labels, all clear of the ink and of each other"
          % (name, len(P.items)))


# ==================================================================== 1
def fig_quadric():
    """x^2 + y^2 - z^2 = 1, both rulings, and a secant meeting it twice."""
    cam = Camera(eye=(7.4, -6.6, 3.9), target=(0, 0, 0.0), focal=8.4,
                 scale=2.55)
    sc, P = Scene(cam), Placer()

    ZMAX = 1.45

    def quad(u, v):
        r = math.sqrt(1.0 + v * v)
        return (r * math.cos(u), r * math.sin(u), v)

    sc.surface(quad, (0, 2 * math.pi), (-ZMAX, ZMAX), 96, 30,
               base="PIndigo", opacity=0.30, ambient=0.50, diffuse=0.50)

    # the two rulings: through (cos t, sin t, 0) with directions
    # (-sin t, cos t, 1) and (-sin t, cos t, -1)
    # a light coordinate frame, so the surface is read against something
    for v, lab in (((2.15, 0, 0), None), ((0, 2.15, 0), None),
                   ((0, 0, 1.95), None)):
        sc.polyline([(0, 0, 0), v],
                    "PSlate,line width=0.45pt,opacity=0.75,"
                    "-{Stealth[length=3.4pt]}")
    sc.curve(lambda t: (math.cos(t), math.sin(t), 0.0), (0, 2 * math.pi), 120,
             "PInk,line width=0.75pt,opacity=0.85", chunk=2)

    for sgn, col in ((+1, "PTeal"), (-1, "PAmber")):
        for k in range(26):
            t = 2 * math.pi * k / 26.0
            b = (math.cos(t), math.sin(t), 0.0)
            d = (-math.sin(t), math.cos(t), float(sgn))
            sc.curve(lambda s, b=b, d=d: addv(b, smul(s, d)),
                     (-ZMAX, ZMAX), 26,
                     "%s,line width=0.62pt,opacity=0.92" % col, chunk=2)

    # a rational line meeting the quadric in two conjugate points:
    # the line x = 1.32, z = 0.40 y meets x^2+y^2-z^2 = 1 where
    # y^2 (1 - 0.16) = 1 - 1.7424, which has no real solution, so take
    # instead a genuine secant and mark the two real points it meets.
    A0 = (0.30, -1.34, -0.55)
    A1 = (0.30, 1.34, 0.55)
    sc.polyline([A0, A1], "PMag,line width=1.4pt")
    # the two intersections, computed from the equation along the segment
    for s in (-1.0, 1.0):
        mid = smul(0.5, addv(A0, A1))
        dirv = smul(0.5, sub(A1, A0))
        # solve |mid + s' dir|^2_{(1,1,-1)} = 1 for s'
        a = dirv[0] ** 2 + dirv[1] ** 2 - dirv[2] ** 2
        b = 2 * (mid[0] * dirv[0] + mid[1] * dirv[1] - mid[2] * dirv[2])
        c = mid[0] ** 2 + mid[1] ** 2 - mid[2] ** 2 - 1.0
        disc = b * b - 4 * a * c
        sp = (-b + s * math.sqrt(max(disc, 0.0))) / (2 * a)
        sc.dot3(addv(mid, smul(sp, dirv)),
                "circle,fill=PMag,draw=white,line width=0.6pt,inner sep=2.1pt")

    P.add((0.0, 0.0, ZMAX), r"$Q:\ x^{2}+y^{2}-z^{2}=1$", "text=PIndigo",
          side="R")
    P.add((1.0, 0.0, 0.95), r"one ruling", "text=PTeal", side="R")
    P.add((1.0, 0.0, 0.0), r"the equator $z=0$", "text=PInk", side="L")
    P.add((1.0, 0.0, -0.95), r"the other ruling", "text=PAmber", side="R")
    P.add(A1, r"$[e^{+st}]$", "text=PMag", side="R")
    P.add(A0, r"$[e^{-st}]$", "text=PMag", side="L")
    P.add(smul(0.5, addv(A0, A1)), r"$P_{t}$, over $\QQ$", "text=PMag",
          side="L")
    write("fig_quadric",
          "The even spinor variety in the smallest case: a smooth quadric "
          "with its two rulings, and the rational secant meeting it twice.",
          sc, P)


# ==================================================================== 2
def fig_lagsweep():
    """A pencil of planes through a common line: the fan of Lagrangians."""
    cam = Camera(eye=(5.0, -7.6, 4.6), target=(0, 0, 0.0), focal=8.6,
                 scale=2.30)
    sc, P = Scene(cam), Placer()

    R = 1.55
    axis = (1.0, 0.0, 0.0)
    fan = [(-1.16, "PSlate", 0.20, False), (-0.92, "PIndigo", 0.22, False),
           (-0.64, "PViolet", 0.24, False), (-0.36, "PTeal", 0.38, True),
           (-0.12, "PBlue", 0.22, False), (0.12, "PGrass", 0.22, False),
           (0.36, "PAmber", 0.38, True), (0.64, "PClay", 0.24, False),
           (0.92, "PMag", 0.22, False), (1.16, "PSlate", 0.20, False)]
    for th, col, op, rational in fan:
        e2 = (0.0, math.cos(th), math.sin(th))

        def plane(u, v, e2=e2):
            return addv(smul(R * v * math.cos(u), axis),
                        smul(R * v * math.sin(u), e2))
        sc.surface(plane, (0, 2 * math.pi), (0.05, 1.0), 60, 8,
                   base=col, opacity=op, ambient=0.48, diffuse=0.48)
        sc.curve(lambda u, e2=e2: addv(smul(R * math.cos(u), axis),
                                       smul(R * math.sin(u), e2)),
                 (0, 2 * math.pi), 96,
                 "%s,line width=%.2fpt" % (col, 1.15 if rational else 0.55),
                 chunk=2)

    sc.polyline([(-R * 1.16, 0, 0), (R * 1.16, 0, 0)],
                "PInk,line width=1.0pt")
    sc.dot3((0, 0, 0), "circle,fill=PInk,inner sep=1.5pt,draw=none")

    P.add((0.0, R * math.cos(-0.36), R * math.sin(-0.36)),
          r"$\psi\in\End^{0}(A)$", "text=PTeal", side="L")
    P.add((0.0, R * math.cos(0.36), R * math.sin(0.36)),
          r"$\psi'\in\End^{0}(A)$", "text=PAmber", side="R")
    P.add((0.0, R * math.cos(1.16), R * math.sin(1.16)),
          r"$\psi$ real: the fan is a continuum", "text=PSlate", side="R")
    P.add((0.0, R * math.cos(-1.16), R * math.sin(-1.16)),
          r"each leaf is an $\mathrm{LG}(n,2n)$", "text=PViolet", side="L")
    P.add((R * 1.16, 0, 0), r"the common axis", side="R")
    write("fig_lagsweep",
          "The fan of Lagrangian loci: each psi gives one leaf, the real psi "
          "sweep the family, the rational psi pick out countably many.",
          sc, P)


# ==================================================================== 3
def fig_fibres():
    """The null cone, the two conjugate isotropic planes, and the fibres."""
    cam = Camera(eye=(6.4, -8.0, 4.5), target=(0, 0, 0.10), focal=8.2,
                 scale=2.45)
    sc, P = Scene(cam), Placer()

    for sgn in (1, -1):
        sc.surface(lambda u, v, s=sgn: (v * math.cos(u), v * math.sin(u),
                                        s * v),
                   (0, 2 * math.pi), (0.05, 2.30), 90, 16,
                   base="PSlate", opacity=0.26, ambient=0.54, diffuse=0.38)
        # rulings of the cone, so it reads as a ruled surface and not a blob
        for k in range(24):
            t = 2 * math.pi * k / 24.0
            sc.curve(lambda s, t=t, sg=sgn: (s * math.cos(t), s * math.sin(t),
                                             sg * s),
                     (0.05, 2.30), 10,
                     "PSlate,line width=0.32pt,opacity=0.55", chunk=3)

    for v in ((2.45, 0, 0), (0, 2.45, 0), (0, 0, 2.55)):
        sc.polyline([(0, 0, 0), v],
                    "PSlate,line width=0.45pt,opacity=0.7,"
                    "-{Stealth[length=3.4pt]}")

    sc.surface(lambda u, v: (u, v, u + v), (-1.5, 1.5), (-1.5, 1.5), 24, 24,
               base="PIndigo", opacity=0.50, ambient=0.44, diffuse=0.56)
    sc.surface(lambda u, v: (u, -v, u - v), (-1.5, 1.5), (-1.5, 1.5), 24, 24,
               base="PMag", opacity=0.50, ambient=0.44, diffuse=0.56)

    for k in range(-4, 5):
        t = 0.34 * k
        a, b = (t, t, 2 * t), (t, -t, 0.0)
        sc.polyline([a, b], "PGrass,line width=1.05pt")
        sc.dot3(a, "circle,fill=PIndigo,draw=white,line width=0.45pt,"
                   "inner sep=1.25pt")
        sc.dot3(b, "circle,fill=PMag,draw=white,line width=0.45pt,"
                   "inner sep=1.25pt")

    sc.surface(lambda u, v: (u, u * (1 - 2 * v), 2 * u * (1 - v)),
               (-1.30, 1.30), (0.0, 1.0), 24, 12,
               base="PAmber", opacity=0.54, ambient=0.50, diffuse=0.46)

    P.add((1.42, 1.42, 2.84), r"$V_{+}$", "text=PIndigo", side="R")
    P.add((1.42, -1.42, 0.0), r"$V_{-}$", "text=PMag", side="R")
    P.add((0.30, -0.30, 0.90), r"$V_{+}^{0,1}\otimes V_{-}^{0,1}$",
          "text=PAmber", side="L")
    P.add((1.62, 0.0, 1.62), r"$q=x^{2}+y^{2}-z^{2}=0$", "text=PSlate", side="R")
    P.add((-1.20, -1.20, 0.0), r"fibres", "text=PGrass", side="L")
    write("fig_fibres",
          "The null cone with its rulings, the two conjugate isotropic "
          "planes, the fibres joining them, and the mixed block.",
          sc, P)


if __name__ == "__main__":
    fig_quadric()
    fig_lagsweep()
    fig_fibres()
    print("three plates written")
